<x-app-layout>
<x-slot name="header"><div><h2 class="font-black text-xl text-gray-900">Marketing Campaigns</h2><p class="text-sm text-gray-500 mt-1">Global view of campaigns created by businesses.</p></div></x-slot>
<div class="py-8"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
<div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-7">
@foreach([['Campaigns',$stats['campaigns']],['Active',$stats['active']],['Businesses',$stats['businesses']],['Total Leads',$stats['leads']]] as $stat)<div class="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div class="text-xs font-black uppercase tracking-wider text-gray-400">{{ $stat[0] }}</div><div class="mt-2 text-3xl font-black text-teal-800">{{ number_format($stat[1]) }}</div></div>@endforeach
</div>
<div class="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-gray-50 text-xs uppercase tracking-wide text-gray-500"><tr><th class="px-6 py-3">Campaign</th><th class="px-6 py-3">Business</th><th class="px-6 py-3">Status</th><th class="px-6 py-3">Leads</th><th class="px-6 py-3">Created</th><th class="px-6 py-3">Actions</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($campaigns as $campaign)<tr class="align-top hover:bg-teal-50/30"><td class="px-6 py-4"><div class="font-bold">{{ $campaign->name }}</div><div class="text-xs text-gray-500">/{{ $campaign->slug }}</div></td><td class="px-6 py-4">{{ $campaign->owner?->name ?? $campaign->owner?->email ?? '—' }}</td><td class="px-6 py-4"><span class="rounded-full px-3 py-1 text-xs font-black {{ $campaign->status === 'active' ? 'bg-emerald-100 text-emerald-700' : ($campaign->status === 'paused' ? 'bg-amber-100 text-amber-700' : 'bg-gray-100 text-gray-600') }}">{{ ucfirst($campaign->status) }}</span></td><td class="px-6 py-4 font-bold">{{ number_format($campaign->leads_count) }}</td><td class="px-6 py-4 whitespace-nowrap text-gray-500">{{ $campaign->created_at->format('d M Y') }}</td><td class="px-6 py-4"><div class="flex flex-wrap gap-2"><a class="rounded-lg bg-teal-700 px-3 py-2 text-xs font-black text-white hover:bg-teal-800" href="{{ route('admin.marketing-campaigns.leads', $campaign) }}">View leads</a><a class="rounded-lg border border-gray-200 px-3 py-2 text-xs font-black text-gray-700 hover:bg-gray-50" href="{{ route('admin.marketing-campaigns.download', $campaign) }}">Download CSV</a><a class="rounded-lg border border-gray-200 px-3 py-2 text-xs font-black text-gray-700 hover:bg-gray-50" target="_blank" rel="noopener" href="{{ route('marketing.campaign.show', $campaign) }}">Open form</a></div></td></tr>@empty<tr><td colspan="6" class="px-6 py-12 text-center text-gray-500">No marketing campaigns have been created yet.</td></tr>@endforelse</tbody></table></div>@if($campaigns->hasPages())<div class="border-t px-6 py-4">{{ $campaigns->links() }}</div>@endif</div>
<div class="mt-7 rounded-2xl border border-teal-100 bg-teal-50 p-5"><h3 class="font-black text-teal-900">Turn lead data into revenue</h3><p class="mt-1 text-sm leading-6 text-teal-800">Use campaign-level lead volume and UTM data to identify high-performing businesses, offers and acquisition channels. The next useful layer is campaign analytics, lead quality scoring, conversion tracking and segmented follow-up.</p></div>
</div></div>
</x-app-layout>
