<x-app-layout>
<x-slot name="header"><h2 class="font-semibold text-xl text-gray-800">Create Social Follow Campaign</h2></x-slot>
<div class="py-10"><div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><form method="POST" action="{{ route('business.social-follow.store') }}" class="space-y-6">@csrf
<div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h3 class="text-lg font-bold">Campaign</h3><div class="mt-5 grid gap-5"><div><label class="text-sm font-medium">Campaign name</label><input name="name" value="{{ old('name') }}" required class="mt-1 w-full rounded-lg border-gray-300"></div><div><label class="text-sm font-medium">Headline</label><input name="headline" value="{{ old('headline') }}" placeholder="Follow us & unlock your free resource" class="mt-1 w-full rounded-lg border-gray-300"></div><div><label class="text-sm font-medium">Description</label><textarea name="description" rows="3" class="mt-1 w-full rounded-lg border-gray-300">{{ old('description') }}</textarea></div></div></div>
<div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h3 class="text-lg font-bold">Social platforms</h3><p class="mt-1 text-sm text-gray-500">Only your business account details are collected. Customers are never asked for their social handles.</p><div class="mt-5 grid gap-5 md:grid-cols-2">@foreach($platforms as $platform)<div class="rounded-xl border p-4"><label class="flex items-center gap-3"><input type="checkbox" name="platforms[]" value="{{ $platform }}" @checked(in_array($platform, old('platforms', []))) class="rounded"> <span class="font-semibold capitalize">{{ $platform }}</span></label><input name="handles[{{ $platform }}]" value="{{ old('handles.'.$platform) }}" placeholder="Business handle (optional)" class="mt-3 w-full rounded-lg border-gray-300 text-sm"><input name="profile_urls[{{ $platform }}]" value="{{ old('profile_urls.'.$platform, $accounts[$platform]->profile_url ?? '') }}" placeholder="https://{{ $platform }}.com/youraccount" class="mt-2 w-full rounded-lg border-gray-300 text-sm"></div>@endforeach</div></div>
<div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h3 class="text-lg font-bold">Unlock requirement</h3><div class="mt-5 max-w-xs"><label class="text-sm font-medium">Minimum score</label><input type="number" min="1" name="minimum_score" value="{{ old('minimum_score', 1) }}" required class="mt-1 w-full rounded-lg border-gray-300"><p class="mt-1 text-xs text-gray-500">Each selected platform is worth 1 point.</p></div></div>
<div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h3 class="text-lg font-bold">Reward / Resource</h3><div class="mt-5 grid gap-5"><select name="resource_type" class="rounded-lg border-gray-300"><option value="external_link">External link</option><option value="download">Download</option></select><input name="resource_title" value="{{ old('resource_title') }}" required placeholder="e.g. Free AI Ebook" class="rounded-lg border-gray-300"><input name="resource_url" value="{{ old('resource_url') }}" required type="url" placeholder="https://..." class="rounded-lg border-gray-300"></div></div>
@if($errors->any())<div class="rounded-lg bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<div class="flex justify-end gap-3"><a href="{{ route('business.social-follow.index') }}" class="rounded-lg border px-5 py-3">Cancel</a><button class="rounded-lg bg-indigo-600 px-5 py-3 font-semibold text-white">Create Campaign</button></div>
</form></div></div></x-app-layout>
