<x-app-layout>
<x-slot name="header"><h2 class="font-semibold text-xl text-gray-800">Edit Social Follow Campaign</h2></x-slot>
<div class="py-10"><div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><form method="POST" action="{{ route('business.social-follow.update', $campaign) }}" class="space-y-6">@csrf @method('PUT')
<div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h3 class="text-lg font-bold">Campaign</h3><div class="mt-5 grid gap-5"><input name="name" value="{{ old('name', $campaign->name) }}" required class="rounded-lg border-gray-300"><input name="headline" value="{{ old('headline', $campaign->headline) }}" class="rounded-lg border-gray-300"><textarea name="description" rows="3" class="rounded-lg border-gray-300">{{ old('description', $campaign->description) }}</textarea></div></div>
@php($selected=$campaign->socialAccounts->keyBy('platform'))
<div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h3 class="text-lg font-bold">Social platforms</h3><p class="mt-1 text-sm text-gray-500">Customers are not asked for their handles.</p><div class="mt-5 grid gap-5 md:grid-cols-2">@foreach($platforms as $platform)<div class="rounded-xl border p-4"><label class="flex items-center gap-3"><input type="checkbox" name="platforms[]" value="{{ $platform }}" @checked($selected->has($platform)) class="rounded"><span class="font-semibold capitalize">{{ $platform }}</span></label><input name="handles[{{ $platform }}]" value="{{ old('handles.'.$platform, $selected[$platform]->handle ?? '') }}" placeholder="Business handle (optional)" class="mt-3 w-full rounded-lg border-gray-300 text-sm"><input name="profile_urls[{{ $platform }}]" value="{{ old('profile_urls.'.$platform, $selected[$platform]->profile_url ?? '') }}" placeholder="Profile URL" class="mt-2 w-full rounded-lg border-gray-300 text-sm"></div>@endforeach</div></div>
<div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><label class="text-sm font-medium">Minimum score</label><input type="number" min="1" name="minimum_score" value="{{ old('minimum_score', $campaign->minimum_score) }}" required class="mt-1 w-full max-w-xs rounded-lg border-gray-300"><div class="mt-4"><label class="flex items-center gap-2"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $campaign->is_active)) class="rounded"> <span>Campaign active</span></label></div></div>
<div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h3 class="text-lg font-bold">Reward / Resource</h3><div class="mt-5 grid gap-5"><select name="resource_type" class="rounded-lg border-gray-300"><option value="external_link" @selected($campaign->resource_type==='external_link')>External link</option><option value="download" @selected($campaign->resource_type==='download')>Download</option></select><input name="resource_title" value="{{ old('resource_title', $campaign->resource_title) }}" required class="rounded-lg border-gray-300"><input name="resource_url" value="{{ old('resource_url', $campaign->resource_url) }}" required type="url" class="rounded-lg border-gray-300"></div></div>
@if($errors->any())<div class="rounded-lg bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<div class="flex justify-end gap-3"><a href="{{ route('business.social-follow.index') }}" class="rounded-lg border px-5 py-3">Cancel</a><button class="rounded-lg bg-indigo-600 px-5 py-3 font-semibold text-white">Save Changes</button></div>
</form></div></div></x-app-layout>
