<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><h2 class="font-semibold text-xl text-gray-800">Social Follow Campaigns</h2><a href="{{ route('business.social-follow.create') }}" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">+ Create Campaign</a></div></x-slot>
    <div class="py-10"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        @if(session('success'))<div class="mb-5 rounded-lg bg-green-50 p-4 text-green-700">{{ session('success') }}</div>@endif
        <div class="mb-6 rounded-2xl bg-gradient-to-r from-indigo-600 to-purple-600 p-6 text-white shadow"><p class="text-sm opacity-80">{{ $business->name }}</p><h1 class="mt-1 text-2xl font-bold">Turn followers into a reward journey.</h1><p class="mt-2 max-w-2xl text-sm opacity-90">Create a campaign, choose your social platforms, set the score required, and send customers to a resource after they complete the gate.</p></div>
        @forelse($campaigns as $campaign)
            <div class="mb-4 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div class="flex flex-wrap gap-2">@foreach($campaign->socialAccounts as $account)<span class="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium capitalize">{{ $account->platform }}</span>@endforeach</div><h3 class="mt-3 text-lg font-bold">{{ $campaign->name }}</h3><p class="text-sm text-gray-500">Required score: {{ $campaign->minimum_score }} · Resource: {{ $campaign->resource_title }}</p></div><div class="flex gap-2"><a class="rounded-lg border px-4 py-2 text-sm" target="_blank" href="{{ route('social-follow.show', [$business->slug, $campaign->slug]) }}">Preview</a><a class="rounded-lg bg-gray-900 px-4 py-2 text-sm text-white" href="{{ route('business.social-follow.edit', $campaign) }}">Edit</a></div></div><div class="mt-4 rounded-lg bg-gray-50 p-3 text-xs text-gray-600 break-all">{{ route('social-follow.show', [$business->slug, $campaign->slug]) }}</div></div>
        @empty
            <div class="rounded-2xl bg-white p-12 text-center shadow-sm ring-1 ring-gray-200"><div class="text-4xl">🚀</div><h3 class="mt-4 text-xl font-bold">Create your first campaign</h3><p class="mx-auto mt-2 max-w-md text-sm text-gray-500">Give customers a reason to follow your social accounts, then unlock your resource when they reach the required score.</p><a href="{{ route('business.social-follow.create') }}" class="mt-6 inline-block rounded-lg bg-indigo-600 px-5 py-3 font-semibold text-white">Create Campaign</a></div>
        @endforelse
    </div></div>
</x-app-layout>
