<x-app-layout>
<x-slot name="header"><div><p class="text-xs font-black uppercase tracking-widest text-blue-600">People & network</p><h2 class="font-black text-2xl text-gray-900">Partners</h2><p class="text-sm text-gray-500 mt-1">Approval status, recruiter, sales, earnings and network growth in one scan.</p></div></x-slot>
<div class="py-6 bg-slate-50 min-h-screen"><div class="max-w-[1600px] mx-auto px-4 sm:px-6 lg:px-8">@include('admin.partials.command-nav')
@if(session('success'))<div class="mb-4 rounded-2xl bg-emerald-50 border border-emerald-200 p-4 text-emerald-700">{{session('success')}}</div>@endif @if(session('error'))<div class="mb-4 rounded-2xl bg-rose-50 border border-rose-200 p-4 text-rose-700">{{session('error')}}</div>@endif
<div class="rounded-2xl border bg-white shadow-sm overflow-hidden"><div class="p-5 border-b flex items-center justify-between"><div><h3 class="font-black">Partner directory</h3><p class="text-sm text-slate-500">Use the row to understand performance before opening the partner.</p></div><a href="{{route('network.index')}}" class="rounded-xl border px-4 py-2 text-sm font-black">Network tree →</a></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4 text-left">Partner</th><th class="p-4 text-left">Business / Program</th><th class="p-4 text-left">Recruiter</th><th class="p-4">Status</th><th class="p-4">Recruits</th><th class="p-4 text-right">Sales</th><th class="p-4 text-right">Earnings</th><th class="p-4">Approval</th></tr></thead><tbody class="divide-y">@forelse($partners as $partner)<tr class="hover:bg-blue-50/30"><td class="p-4"><div class="font-black">{{ $partner->user->name }}</div><div class="text-xs text-slate-400">{{ $partner->user->email }} · {{ $partner->partner_code }}</div></td><td class="p-4"><div class="font-bold">{{ $partner->program->name }}</div><div class="text-xs text-slate-400">Program</div></td><td class="p-4">{{ $partner->parentPartner?->user?->name ?? 'Direct / none' }}</td><td class="p-4"><span class="rounded-full px-2.5 py-1 text-xs font-black {{ $partner->status === 'active' ? 'bg-emerald-100 text-emerald-700' : ($partner->status === 'pending' ? 'bg-amber-100 text-amber-700' : 'bg-rose-100 text-rose-700') }}">{{ ucfirst($partner->status) }}</span></td><td class="p-4 text-center font-black">{{ $partner->recruits_count }}</td><td class="p-4 text-right font-black">₦{{ number_format($partner->admin_metrics['sales'],2) }}<small class="block text-xs text-slate-400">{{ $partner->admin_metrics['orders'] }} orders</small></td><td class="p-4 text-right font-black text-violet-700">₦{{ number_format($partner->earnings ?? 0,2) }}</td><td class="p-4"><div class="flex flex-wrap gap-2">
@if($partner->status === 'pending')
    @if($superAdminApprovalRequired && !$partner->super_admin_approved_at)
        <form method="POST" action="{{route('admin.partners.approve',$partner)}}">@csrf @method('PATCH')<button class="rounded-lg bg-emerald-600 text-white px-3 py-2 text-xs font-black">Approve platform</button></form>
    @endif
    @if(($partner->program->settings['partner_business_approval_required'] ?? false) && !$partner->business_approved_at)
        <form method="POST" action="{{route('admin.partners.approve-for-business',$partner)}}">@csrf @method('PATCH')<button class="rounded-lg bg-blue-600 text-white px-3 py-2 text-xs font-black">Approve for business</button></form>
    @endif
    <form method="POST" action="{{route('admin.partners.reject',$partner)}}">@csrf @method('PATCH')<button class="rounded-lg border border-rose-200 bg-rose-50 text-rose-700 px-3 py-2 text-xs font-black">Reject</button></form>
@else
    <span class="text-xs text-slate-400">{{ $partner->user->hasVerifiedEmail() ? 'Email verified' : 'Email pending' }}</span>
@endif
</div></td></tr>@empty<tr><td colspan="8" class="p-10 text-center text-slate-400">No partners found.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{$partners->links()}}</div></div>
</div></div></x-app-layout>
