<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Turn your valuable resources into lead-generation campaigns. Collect customer details, ask qualifying questions and send people to the resource they want.">
<meta property="og:title" content="Resource Gate — Turn Resources Into Leads | AIPM">
<meta property="og:description" content="Capture customer details, ask a few smart questions and redirect them to your resource automatically.">
<title>Resource Gate — Turn Resources Into Leads | AIPM</title>
<script src="https://cdn.tailwindcss.com"></script>
<style>html{scroll-behavior:smooth}body{background:#f6fffd;color:#073b3a}.gridbg{background-image:linear-gradient(rgba(13,148,136,.055) 1px,transparent 1px),linear-gradient(90deg,rgba(13,148,136,.055) 1px,transparent 1px);background-size:40px 40px}.grad{background:linear-gradient(90deg,#0f766e,#14b8a6,#2dd4bf);-webkit-background-clip:text;background-clip:text;color:transparent}.glow{background:radial-gradient(circle,rgba(45,212,191,.25),transparent 68%)}</style>
</head>
<body class="font-sans antialiased">
<nav class="fixed inset-x-0 top-0 z-50 border-b border-teal-100 bg-white/85 backdrop-blur-xl"><div class="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="{{ route('home') }}" class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-teal-950 font-black text-white">A</span><span class="text-xl font-black tracking-tight">AIPM</span></a><div class="hidden gap-8 text-sm font-bold text-teal-900/65 md:flex"><a href="#how">How it works</a><a href="#benefits">Benefits</a><a href="#use-cases">Use cases</a></div><a href="{{ route('register') }}" class="rounded-xl bg-teal-700 px-5 py-3 text-sm font-black text-white shadow-lg shadow-teal-700/20 hover:bg-teal-800">Start Capturing Leads</a></div></nav>
<main>
<section class="relative overflow-hidden pt-32 lg:pt-40"><div class="absolute inset-0 gridbg"></div><div class="glow absolute -right-40 top-0 h-[650px] w-[650px]"></div><div class="relative mx-auto grid max-w-7xl items-center gap-14 px-5 pb-24 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-32">
<div><span class="inline-flex rounded-full border border-teal-200 bg-teal-50 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-teal-700">Lead capture made simple</span><h1 class="mt-7 max-w-4xl text-5xl font-black leading-[.98] tracking-[-.045em] text-teal-950 sm:text-6xl lg:text-7xl">Give away your resource. <span class="grad">Keep the lead.</span></h1><p class="mt-7 max-w-2xl text-lg leading-8 text-teal-900/65 sm:text-xl">Turn ebooks, guides, checklists, courses and exclusive downloads into lead-generation campaigns. Collect the information you need, ask a few useful questions, then send people straight to the resource.</p><div class="mt-9 flex flex-col gap-3 sm:flex-row"><a href="{{ route('register') }}" class="rounded-2xl bg-teal-700 px-7 py-4 text-center font-black text-white shadow-xl shadow-teal-700/20 hover:-translate-y-1 hover:bg-teal-800">Create Your First Lead Campaign →</a><a href="#how" class="rounded-2xl border border-teal-200 bg-white px-7 py-4 text-center font-bold text-teal-900 hover:border-teal-400">See How It Works</a></div><div class="mt-8 flex flex-wrap gap-5 text-sm font-bold text-teal-900/55"><span>✓ Capture contact details</span><span>✓ Ask custom questions</span><span>✓ Redirect automatically</span></div></div>
<div class="relative"><div class="absolute -inset-8 rounded-[3rem] bg-teal-400/15 blur-3xl"></div><div class="relative rounded-[2rem] border border-teal-100 bg-white p-4 shadow-2xl shadow-teal-950/10"><div class="rounded-[1.5rem] bg-teal-950 p-6 text-white sm:p-8"><div class="flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-widest text-teal-300">Your resource campaign</p><p class="mt-1 text-xl font-black">Free AI Content Guide</p></div><span class="rounded-full bg-teal-400/10 px-3 py-1.5 text-xs font-bold text-teal-300">Step 2 of 3</span></div><div class="mt-7 flex gap-2"><span class="h-1.5 flex-1 rounded-full bg-teal-400"></span><span class="h-1.5 flex-1 rounded-full bg-teal-400"></span><span class="h-1.5 flex-1 rounded-full bg-white/10"></span></div><div class="mt-7 rounded-2xl bg-white p-5 text-teal-950"><p class="text-xs font-black uppercase tracking-widest text-teal-600">A quick question</p><h3 class="mt-2 text-lg font-black">What do you want to use AI for?</h3><div class="mt-4 space-y-2"><div class="rounded-xl border-2 border-teal-500 bg-teal-50 p-3 font-bold">Content creation</div><div class="rounded-xl border border-slate-200 p-3 font-medium">Business growth</div><div class="rounded-xl border border-slate-200 p-3 font-medium">Learning</div></div><div class="mt-4 rounded-xl bg-teal-700 p-3 text-center font-black text-white">Continue →</div></div><div class="mt-4 flex items-center gap-3 rounded-2xl bg-white/5 p-4"><span class="grid h-10 w-10 place-items-center rounded-xl bg-teal-400 text-teal-950">✓</span><div><p class="font-bold">Almost there</p><p class="text-xs text-teal-200/60">Your resource is ready after the final step.</p></div></div></div></div></div>
</div></section>
<section class="border-y border-teal-100 bg-white"><div class="mx-auto grid max-w-7xl grid-cols-2 sm:grid-cols-4"><div class="border-r border-teal-100 p-7 text-center"><p class="text-3xl font-black text-teal-950">01</p><p class="mt-1 text-sm font-bold text-teal-900/55">Capture</p></div><div class="border-r border-teal-100 p-7 text-center"><p class="text-3xl font-black text-teal-950">02</p><p class="mt-1 text-sm font-bold text-teal-900/55">Qualify</p></div><div class="border-r border-teal-100 p-7 text-center"><p class="text-3xl font-black text-teal-950">03</p><p class="mt-1 text-sm font-bold text-teal-900/55">Redirect</p></div><div class="p-7 text-center"><p class="text-3xl font-black text-teal-950">∞</p><p class="mt-1 text-sm font-bold text-teal-900/55">Follow up</p></div></div></section>
<section id="how" class="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div class="mx-auto max-w-2xl text-center"><span class="text-sm font-black uppercase tracking-[.2em] text-teal-600">How it works</span><h2 class="mt-4 text-4xl font-black tracking-tight text-teal-950 sm:text-5xl">A tiny form. A much bigger marketing opportunity.</h2></div><div class="mt-14 grid gap-6 md:grid-cols-3"><div class="rounded-3xl border border-teal-100 bg-white p-8 shadow-sm"><span class="grid h-12 w-12 place-items-center rounded-2xl bg-teal-50 font-black text-teal-700">01</span><h3 class="mt-6 text-xl font-black">Collect the essentials</h3><p class="mt-3 leading-7 text-teal-900/55">Ask for name, email, phone or any other customer information that matters to your business.</p></div><div class="rounded-3xl border border-teal-100 bg-white p-8 shadow-sm"><span class="grid h-12 w-12 place-items-center rounded-2xl bg-teal-50 font-black text-teal-700">02</span><h3 class="mt-6 text-xl font-black">Ask smart questions</h3><p class="mt-3 leading-7 text-teal-900/55">Add a few custom questions to understand your audience, segment leads and learn what they need.</p></div><div class="rounded-3xl border border-teal-100 bg-white p-8 shadow-sm"><span class="grid h-12 w-12 place-items-center rounded-2xl bg-teal-50 font-black text-teal-700">03</span><h3 class="mt-6 text-xl font-black">Deliver instantly</h3><p class="mt-3 leading-7 text-teal-900/55">After submission, send the person directly to the configured resource. No awkward waiting screen.</p></div></div></section>
<section id="benefits" class="bg-teal-950 text-white"><div class="mx-auto grid max-w-7xl gap-14 px-5 py-24 lg:grid-cols-2 lg:px-8 lg:items-center"><div><span class="text-sm font-black uppercase tracking-[.2em] text-teal-300">Why use Resource Gate?</span><h2 class="mt-4 text-4xl font-black sm:text-5xl">Your free resource can do more than just get downloaded.</h2><p class="mt-6 text-lg leading-8 text-teal-100/60">Use every resource as a structured touchpoint for building your customer database and understanding your audience.</p><a href="{{ route('register') }}" class="mt-8 inline-flex rounded-2xl bg-teal-400 px-6 py-4 font-black text-teal-950 hover:bg-teal-300">Start Capturing Leads →</a></div><div class="grid gap-4 sm:grid-cols-2"><div class="rounded-3xl border border-white/10 bg-white/5 p-7"><div class="text-3xl">👤</div><h3 class="mt-4 text-xl font-black">Know your audience</h3><p class="mt-2 leading-7 text-teal-100/55">Collect the details that help you build useful customer profiles.</p></div><div class="rounded-3xl border border-white/10 bg-white/5 p-7"><div class="text-3xl">🧠</div><h3 class="mt-4 text-xl font-black">Learn what they want</h3><p class="mt-2 leading-7 text-teal-100/55">Use questions to discover interests, needs and intent.</p></div><div class="rounded-3xl border border-white/10 bg-white/5 p-7"><div class="text-3xl">⚡</div><h3 class="mt-4 text-xl font-black">Instant delivery</h3><p class="mt-2 leading-7 text-teal-100/55">Send people to the promised resource immediately after submission.</p></div><div class="rounded-3xl border border-white/10 bg-white/5 p-7"><div class="text-3xl">📈</div><h3 class="mt-4 text-xl font-black">Build your pipeline</h3><p class="mt-2 leading-7 text-teal-100/55">Turn resource downloads into an audience you can nurture.</p></div></div></div></section>
<section id="use-cases" class="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div class="text-center"><span class="text-sm font-black uppercase tracking-[.2em] text-teal-600">Built for any resource</span><h2 class="mt-4 text-4xl font-black text-teal-950 sm:text-5xl">If you can give it away, you can gate it.</h2></div><div class="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-3xl border border-teal-100 bg-white p-7"><h3 class="text-xl font-black">📕 Ebooks</h3><p class="mt-2 text-teal-900/55">Capture readers before delivering your book.</p></div><div class="rounded-3xl border border-teal-100 bg-white p-7"><h3 class="text-xl font-black">📋 Checklists</h3><p class="mt-2 text-teal-900/55">Exchange a useful checklist for qualified leads.</p></div><div class="rounded-3xl border border-teal-100 bg-white p-7"><h3 class="text-xl font-black">🎓 Courses</h3><p class="mt-2 text-teal-900/55">Qualify learners before sending them to content.</p></div><div class="rounded-3xl border border-teal-100 bg-white p-7"><h3 class="text-xl font-black">🎁 Downloads</h3><p class="mt-2 text-teal-900/55">Gate templates, files, offers and exclusive resources.</p></div></div></section>
<section class="px-5 pb-24 lg:px-8"><div class="mx-auto max-w-5xl rounded-[2.5rem] bg-gradient-to-br from-teal-700 to-teal-950 px-7 py-16 text-center text-white shadow-2xl sm:px-12"><span class="text-sm font-black uppercase tracking-[.2em] text-teal-200">Make your next resource work harder</span><h2 class="mx-auto mt-4 max-w-3xl text-4xl font-black sm:text-5xl">Capture the lead. Learn about them. Deliver the value.</h2><a href="{{ route('register') }}" class="mt-9 inline-flex rounded-2xl bg-white px-7 py-4 font-black text-teal-800 shadow-xl hover:-translate-y-1">Create a Resource Campaign →</a></div></section>
</main><footer class="border-t border-teal-100 bg-white"><div class="mx-auto flex max-w-7xl justify-between px-5 py-8 text-sm lg:px-8"><strong class="text-teal-950">AIPM</strong><span class="text-teal-900/45">Turn resources into relationships.</span></div></footer>
</body></html>