<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
            <div><div class="flex items-center gap-2"><span class="h-2.5 w-2.5 rounded-full bg-emerald-500"></span><span class="text-xs font-black uppercase tracking-widest text-emerald-600">Platform command center</span></div><h2 class="mt-1 font-black text-2xl text-gray-900">Super Admin Dashboard</h2><p class="text-sm text-gray-500">Everything important, prioritized for fast decisions.</p></div>
            <div class="flex flex-wrap gap-2"><a href="{{ route('admin.analytics.businesses') }}" class="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-black text-white">All Businesses →</a><a href="{{ route('network.index') }}" class="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold">Network</a><a href="{{ route('admin.settings') }}" class="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold">Settings</a></div>
        </div>
    </x-slot>

    <div class="py-6 bg-slate-50 min-h-screen"><div class="max-w-[1600px] mx-auto px-4 sm:px-6 lg:px-8 space-y-5">
        <div class="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-3">
            @foreach ([['Businesses',$stats['businesses'],'admin.analytics.businesses','text-violet-700'],['Partners',$stats['partners'],'admin.partners.index','text-blue-700'],['Customers',$stats['customers'],'admin.analytics.show','text-cyan-700'],['Programs',$stats['programs'],'admin.programs.index','text-indigo-700'],['Products',$stats['products'],'admin.products.index','text-slate-700'],['Orders',$stats['paid_orders'].' / '.$stats['orders'],'admin.orders.index','text-amber-700'],['Gross Sales','₦'.number_format($stats['sales'],0),'admin.analytics.show','text-emerald-700'],['Net Revenue','₦'.number_format($stats['net_platform_revenue'],0),'admin.analytics.show','text-teal-700']] as $card)
                <a href="{{ $card[2] === 'admin.analytics.show' ? route($card[2], 'sales') : route($card[2]) }}" class="rounded-2xl bg-white border border-slate-200 p-4 shadow-sm hover:-translate-y-0.5 hover:shadow-md transition"><div class="text-xs font-bold uppercase tracking-wide text-slate-400">{{ $card[0] }}</div><div class="mt-2 text-xl font-black {{ $card[3] }}">{{ $card[1] }}</div><div class="mt-2 text-[11px] font-bold text-slate-400">Open →</div></a>
            @endforeach
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-4 gap-4">
            @foreach($pendingActions as $action)
                <a href="{{ route($action['route']) }}" class="rounded-2xl border bg-white p-4 shadow-sm hover:shadow-md transition"><div class="flex items-center justify-between"><span class="text-sm font-bold text-slate-700">{{ $action['label'] }}</span><span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-black text-amber-700">{{ $action['count'] }}</span></div><p class="mt-2 text-xs text-slate-400">Needs attention now →</p></a>
            @endforeach
        </div>

        <div class="grid grid-cols-1 xl:grid-cols-12 gap-5">
            <section class="xl:col-span-8 rounded-2xl border bg-white shadow-sm overflow-hidden"><div class="p-5 border-b flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-widest text-violet-600">Business command view</p><h3 class="mt-1 text-lg font-black">All businesses at a glance</h3><p class="text-sm text-slate-500">Jump from business → partners → sales without hunting through menus.</p></div><a href="{{ route('admin.analytics.businesses') }}" class="text-sm font-black text-violet-600">Open all →</a></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4 text-left">Business</th><th class="p-4 text-left">Programs</th><th class="p-4 text-left">Partners</th><th class="p-4 text-left">Orders</th><th class="p-4 text-left">Sales</th><th></th></tr></thead><tbody class="divide-y">@forelse($businesses as $business)<tr class="hover:bg-violet-50/40"><td class="p-4"><div class="font-black">{{ $business->business_name ?: $business->name }}</div><div class="text-xs text-slate-400">{{ $business->email }}</div></td><td class="p-4">{{ $business->dashboard_metrics['programs'] }}</td><td class="p-4">{{ $business->dashboard_metrics['partners'] }}</td><td class="p-4">{{ $business->dashboard_metrics['orders'] }}</td><td class="p-4 font-black">₦{{ number_format($business->dashboard_metrics['sales'],0) }}</td><td class="p-4"><a class="font-black text-violet-600" href="{{ route('admin.analytics.business',$business) }}">View →</a></td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-400">No businesses yet.</td></tr>@endforelse</tbody></table></div></section>

            <section class="xl:col-span-4 rounded-2xl border bg-white shadow-sm overflow-hidden"><div class="p-5 border-b"><p class="text-xs font-black uppercase tracking-widest text-emerald-600">Money control</p><h3 class="mt-1 text-lg font-black">Where the money is</h3></div><div class="divide-y"><a href="{{ route('admin.analytics.show','sales') }}" class="flex justify-between p-4 hover:bg-slate-50"><span><b>Gross sales</b><small class="block text-xs text-slate-400">Paid customer orders</small></span><strong>₦{{ number_format($stats['sales'],2) }}</strong></a><a href="{{ route('admin.analytics.show','commissions') }}" class="flex justify-between p-4 hover:bg-slate-50"><span><b>Partner commissions</b><small class="block text-xs text-slate-400">Generated, excluding reversals</small></span><strong>₦{{ number_format($stats['commissions'],2) }}</strong></a><a href="{{ route('admin.payouts.index') }}" class="flex justify-between p-4 hover:bg-slate-50"><span><b>Pending payouts</b><small class="block text-xs text-slate-400">Partner requests</small></span><strong>₦{{ number_format($stats['pending_payouts'],2) }}</strong></a><a href="{{ route('admin.analytics.show','sales') }}" class="flex justify-between p-4 bg-emerald-50/50 hover:bg-emerald-50"><span><b>Platform net</b><small class="block text-xs text-slate-400">Sales less commissions</small></span><strong class="text-emerald-700">₦{{ number_format($stats['net_platform_revenue'],2) }}</strong></a></div></section>
        </div>

        <div class="grid grid-cols-1 xl:grid-cols-5 gap-5">
            <section class="xl:col-span-3 rounded-2xl border bg-white shadow-sm overflow-hidden"><div class="p-5 border-b flex justify-between"><div><p class="text-xs font-black uppercase tracking-widest text-blue-600">Live sales feed</p><h3 class="mt-1 text-lg font-black">Recent customer activity</h3></div><a href="{{ route('admin.orders.index') }}" class="text-sm font-black text-violet-600">All orders →</a></div><div class="divide-y">@forelse($recentOrders as $order)<a href="{{ route('admin.orders.show',$order) }}" class="flex items-center justify-between gap-4 p-4 hover:bg-slate-50"><div><div class="font-bold">{{ $order->customer?->name ?? $order->customer_name ?? 'Guest customer' }}</div><div class="text-xs text-slate-400">{{ $order->order_number }} · {{ $order->program?->name ?? '—' }} · {{ $order->partner?->user?->name ?? 'Direct' }}</div></div><div class="text-right"><div class="font-black">{{ $order->currency }} {{ number_format($order->total,2) }}</div><div class="text-xs text-slate-400">{{ $order->created_at->diffForHumans() }}</div></div></a>@empty<div class="p-8 text-center text-slate-400">No activity.</div>@endforelse</div></section>
            <section class="xl:col-span-2 rounded-2xl border bg-white shadow-sm overflow-hidden"><div class="p-5 border-b"><p class="text-xs font-black uppercase tracking-widest text-violet-600">Partner performance</p><h3 class="mt-1 text-lg font-black">Top earners</h3></div><div class="divide-y">@forelse($topPartners as $partner)<a href="{{ route('admin.analytics.show','partners') }}" class="flex items-center justify-between p-4 hover:bg-slate-50"><div><div class="font-bold">{{ $partner->user?->name ?? 'Unknown' }}</div><div class="text-xs text-slate-400">{{ $partner->program?->name ?? '—' }}</div></div><strong>₦{{ number_format($partner->earnings ?? 0,2) }}</strong></a>@empty<div class="p-8 text-center text-slate-400">No partners yet.</div>@endforelse</div></section>
        </div>

        <section class="rounded-2xl border bg-white shadow-sm overflow-hidden"><div class="p-5 border-b flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-widest text-indigo-600">Program performance</p><h3 class="mt-1 text-lg font-black">Which programs are moving?</h3></div><a href="{{ route('admin.programs.index') }}" class="text-sm font-black text-violet-600">Manage programs →</a></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4 text-left">Program</th><th class="p-4">Status</th><th class="p-4">Partners</th><th class="p-4">Products</th><th class="p-4">Orders</th><th class="p-4 text-right">Sales</th></tr></thead><tbody class="divide-y">@forelse($programs as $program)<tr><td class="p-4 font-black">{{ $program->name }}</td><td class="p-4">{{ ucfirst($program->status) }}</td><td class="p-4 text-center">{{ $program->partners_count }}</td><td class="p-4 text-center">{{ $program->products_count }}</td><td class="p-4 text-center">{{ $program->orders_count }}</td><td class="p-4 text-right font-black">₦{{ number_format($program->sales ?? 0,2) }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-400">No programs yet.</td></tr>@endforelse</tbody></table></div></section>

        <section class="rounded-2xl border bg-slate-900 text-white p-5"><div class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-widest text-violet-300">Fast navigation</p><h3 class="text-lg font-black mt-1">Go straight to the work</h3><p class="text-sm text-slate-300 mt-1">No dashboard hunting: every operational area is one click away.</p></div><div class="flex flex-wrap gap-2">@foreach([['Businesses','admin.businesses.index'],['Partners','admin.partners.index'],['Orders','admin.orders.index'],['Commissions','admin.commissions.index'],['Partner payouts','admin.payouts.index'],['Business payouts','admin.business-payouts.index'],['Analytics','admin.analytics.businesses']] as $link)<a href="{{ route($link[1]) }}" class="rounded-xl bg-white/10 border border-white/10 px-3 py-2 text-xs font-black hover:bg-white/20">{{ $link[0] }}</a>@endforeach</div></div></section>
    </div></div>
</x-app-layout>
