<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
            <div><div class="flex items-center gap-2"><span class="h-2.5 w-2.5 rounded-full bg-emerald-500"></span><span class="text-xs font-black uppercase tracking-widest text-emerald-600">Platform command center</span></div><h2 class="mt-1 font-black text-2xl text-gray-900">Super Admin Dashboard</h2><p class="text-sm text-gray-500">Operational intelligence, financial control and live activity.</p></div>
            <div class="flex flex-wrap gap-2"><a href="{{ route('admin.analytics.businesses') }}" class="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-black text-white">All Businesses →</a><a href="{{ route('network.index') }}" class="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold">Network</a><a href="{{ route('admin.settings') }}" class="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold">Settings</a></div>
        </div>
    </x-slot>

    <div class="py-6 bg-slate-50 min-h-screen"><div class="max-w-[1600px] mx-auto px-4 sm:px-6 lg:px-8 space-y-5">
        <form method="GET" class="rounded-2xl border bg-white p-4 shadow-sm flex flex-col lg:flex-row lg:items-end gap-3">
            <div><label class="block text-xs font-black uppercase tracking-wide text-slate-400">From</label><input type="date" name="from" value="{{ request('from') }}" class="mt-1 rounded-xl border-slate-200 text-sm"></div>
            <div><label class="block text-xs font-black uppercase tracking-wide text-slate-400">To</label><input type="date" name="to" value="{{ request('to') }}" class="mt-1 rounded-xl border-slate-200 text-sm"></div>
            <div class="flex gap-2"><button class="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-black text-white">Apply</button><a href="{{ route('admin') }}" class="rounded-xl border px-4 py-2.5 text-sm font-bold">All time</a></div>
            <div class="lg:ml-auto flex flex-wrap gap-2"><a href="{{ route('admin.analytics.export', array_merge(['metric'=>'sales'], request()->only('from','to'))) }}" class="rounded-xl border px-3 py-2 text-xs font-black">Export sales CSV</a><span class="rounded-xl bg-emerald-50 px-3 py-2 text-xs font-black text-emerald-700">Updated {{ now()->format('H:i:s') }}</span></div>
        </form>

        <div class="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-3">
            @foreach ([['Businesses',$stats['businesses'],'admin.analytics.businesses','text-violet-700'],['Partners',$stats['partners'],'admin.partners.index','text-blue-700'],['Customers',$stats['customers'],'admin.analytics.show','text-cyan-700'],['Programs',$stats['programs'],'admin.programs.index','text-indigo-700'],['Products',$stats['products'],'admin.products.index','text-slate-700'],['Orders',$stats['paid_orders'].' / '.$stats['orders'],'admin.orders.index','text-amber-700'],['Gross Sales','₦'.number_format($stats['sales'],0),'admin.analytics.show','text-emerald-700'],['Net Revenue','₦'.number_format($stats['net_platform_revenue'],0),'admin.analytics.show','text-teal-700']] as $card)
                <a href="{{ $card[2] === 'admin.analytics.show' ? route($card[2], 'sales') : route($card[2]) }}" class="rounded-2xl bg-white border border-slate-200 p-4 shadow-sm hover:-translate-y-0.5 hover:shadow-md transition"><div class="text-xs font-bold uppercase tracking-wide text-slate-400">{{ $card[0] }}</div><div class="mt-2 text-xl font-black {{ $card[3] }}">{{ $card[1] }}</div><div class="mt-2 text-[11px] font-bold text-slate-400">Open →</div></a>
            @endforeach
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-4 gap-4">@foreach($pendingActions as $action)<a href="{{ route($action['route']) }}" class="rounded-2xl border bg-white p-4 shadow-sm hover:shadow-md transition"><div class="flex items-center justify-between"><span class="text-sm font-bold text-slate-700">{{ $action['label'] }}</span><span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-black text-amber-700">{{ $action['count'] }}</span></div><p class="mt-2 text-xs text-slate-400">Needs attention now →</p></a>@endforeach</div>

        <section class="rounded-2xl border bg-white shadow-sm p-5"><div class="flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-widest text-indigo-600">Performance trend</p><h3 class="mt-1 text-lg font-black">Sales, orders and commissions over time</h3></div><span class="text-xs text-slate-400">{{ count($series) }} data points</span></div><div class="mt-5 overflow-x-auto"><canvas id="performanceChart" height="110" class="w-full"></canvas></div></section>

        <div class="grid grid-cols-1 xl:grid-cols-12 gap-5">
            <section class="xl:col-span-8 rounded-2xl border bg-white shadow-sm overflow-hidden"><div class="p-5 border-b flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-widest text-violet-600">Business command view</p><h3 class="mt-1 text-lg font-black">All businesses at a glance</h3><p class="text-sm text-slate-500">Jump from business → partners → sales.</p></div><a href="{{ route('admin.analytics.businesses') }}" class="text-sm font-black text-violet-600">Open all →</a></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4 text-left">Business</th><th class="p-4 text-left">Programs</th><th class="p-4 text-left">Partners</th><th class="p-4 text-left">Orders</th><th class="p-4 text-left">Sales</th><th></th></tr></thead><tbody class="divide-y">@forelse($businesses as $business)<tr class="hover:bg-violet-50/40"><td class="p-4"><div class="font-black">{{ $business->business_name ?: $business->name }}</div><div class="text-xs text-slate-400">{{ $business->email }}</div></td><td class="p-4">{{ $business->dashboard_metrics['programs'] }}</td><td class="p-4">{{ $business->dashboard_metrics['partners'] }}</td><td class="p-4">{{ $business->dashboard_metrics['orders'] }}</td><td class="p-4 font-black">₦{{ number_format($business->dashboard_metrics['sales'],0) }}</td><td class="p-4"><a class="font-black text-violet-600" href="{{ route('admin.analytics.business',$business) }}">View →</a></td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-400">No businesses yet.</td></tr>@endforelse</tbody></table></div></section>
            <section class="xl:col-span-4 rounded-2xl border bg-white shadow-sm overflow-hidden"><div class="p-5 border-b"><p class="text-xs font-black uppercase tracking-widest text-emerald-600">Money control</p><h3 class="mt-1 text-lg font-black">Where the money is</h3></div><div class="divide-y"><a href="{{ route('admin.analytics.show','sales') }}" class="flex justify-between p-4 hover:bg-slate-50"><span><b>Gross sales</b><small class="block text-xs text-slate-400">Paid customer orders</small></span><strong>₦{{ number_format($stats['sales'],2) }}</strong></a><a href="{{ route('admin.analytics.show','commissions') }}" class="flex justify-between p-4 hover:bg-slate-50"><span><b>Partner commissions</b><small class="block text-xs text-slate-400">Excluding reversals</small></span><strong>₦{{ number_format($stats['commissions'],2) }}</strong></a><a href="{{ route('admin.payouts.index') }}" class="flex justify-between p-4 hover:bg-slate-50"><span><b>Pending payouts</b><small class="block text-xs text-slate-400">Partner requests</small></span><strong>₦{{ number_format($stats['pending_payouts'],2) }}</strong></a><a href="{{ route('admin.analytics.show','sales') }}" class="flex justify-between p-4 bg-emerald-50/50"><span><b>Operational net</b><small class="block text-xs text-slate-400">Sales less commissions</small></span><strong class="text-emerald-700">₦{{ number_format($stats['net_platform_revenue'],2) }}</strong></a></div></section>
        </div>

        <div class="grid grid-cols-1 xl:grid-cols-5 gap-5">
            <section class="xl:col-span-3 rounded-2xl border bg-white shadow-sm overflow-hidden"><div class="p-5 border-b flex justify-between"><div><p class="text-xs font-black uppercase tracking-widest text-blue-600">Live sales stream</p><h3 class="mt-1 text-lg font-black">Recent customer activity</h3></div><span id="liveStatus" class="text-xs font-bold text-emerald-600">Connecting…</span></div><div id="salesFeed" class="divide-y">@forelse($recentOrders as $order)<a href="{{ route('admin.orders.show',$order) }}" class="flex items-center justify-between gap-4 p-4 hover:bg-slate-50"><div><div class="font-bold">{{ $order->customer?->name ?? $order->customer_name ?? 'Guest customer' }}</div><div class="text-xs text-slate-400">{{ $order->order_number }} · {{ $order->program?->name ?? '—' }} · {{ $order->partner?->user?->name ?? 'Direct' }}</div></div><div class="text-right"><div class="font-black">{{ $order->currency }} {{ number_format($order->total,2) }}</div><div class="text-xs text-slate-400">{{ $order->created_at->diffForHumans() }}</div></div></a>@empty<div class="p-8 text-center text-slate-400">No activity.</div>@endforelse</div></section>
            <section class="xl:col-span-2 rounded-2xl border bg-white shadow-sm overflow-hidden"><div class="p-5 border-b"><p class="text-xs font-black uppercase tracking-widest text-violet-600">Partner performance</p><h3 class="mt-1 text-lg font-black">Top earners</h3></div><div class="divide-y">@forelse($topPartners as $partner)<a href="{{ route('admin.analytics.show','partners') }}" class="flex items-center justify-between p-4 hover:bg-slate-50"><div><div class="font-bold">{{ $partner->user?->name ?? 'Unknown' }}</div><div class="text-xs text-slate-400">{{ $partner->program?->name ?? '—' }}</div></div><strong>₦{{ number_format($partner->earnings ?? 0,2) }}</strong></a>@empty<div class="p-8 text-center text-slate-400">No partners yet.</div>@endforelse</div></section>
        </div>

        <section class="rounded-2xl border bg-white shadow-sm overflow-hidden"><div class="p-5 border-b flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-widest text-indigo-600">Program performance</p><h3 class="mt-1 text-lg font-black">Which programs are moving?</h3></div><a href="{{ route('admin.programs.index') }}" class="text-sm font-black text-violet-600">Manage programs →</a></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4 text-left">Program</th><th class="p-4">Status</th><th class="p-4">Partners</th><th class="p-4">Products</th><th class="p-4">Orders</th><th class="p-4 text-right">Sales</th></tr></thead><tbody class="divide-y">@forelse($programs as $program)<tr><td class="p-4 font-black">{{ $program->name }}</td><td class="p-4">{{ ucfirst($program->status) }}</td><td class="p-4 text-center">{{ $program->partners_count }}</td><td class="p-4 text-center">{{ $program->products_count }}</td><td class="p-4 text-center">{{ $program->orders_count }}</td><td class="p-4 text-right font-black">₦{{ number_format($program->sales ?? 0,2) }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-400">No programs yet.</td></tr>@endforelse</tbody></table></div></section>
    </div></div>

<script>
const series = @json($series);
const canvas = document.getElementById('performanceChart');
const ctx = canvas.getContext('2d');
function drawChart(){const d=window.devicePixelRatio||1,w=canvas.clientWidth||900,h=220;canvas.width=w*d;canvas.height=h*d;ctx.scale(d,d);ctx.clearRect(0,0,w,h);const vals=series.map(x=>x.sales), max=Math.max(...vals,1), left=42, bottom=30, top=12, right=12;ctx.strokeStyle='#e2e8f0';ctx.lineWidth=1;for(let i=0;i<4;i++){const y=top+(h-top-bottom)*i/3;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(w-right,y);ctx.stroke()}if(!series.length)return;ctx.strokeStyle='#7c3aed';ctx.lineWidth=3;ctx.beginPath();series.forEach((p,i)=>{const x=left+(w-left-right)*(i/Math.max(series.length-1,1)),y=top+(h-top-bottom)*(1-p.sales/max);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#64748b';ctx.font='11px sans-serif';ctx.fillText(series[0].date,left,h-8);ctx.fillText(series[series.length-1].date,w-80,h-8);ctx.fillText('₦'+Math.round(max).toLocaleString(),left,top+10)}drawChart();window.addEventListener('resize',drawChart);
const feed=document.getElementById('salesFeed'), status=document.getElementById('liveStatus');
function connect(){const source=new EventSource('{{ route('admin.realtime.sales') }}');source.addEventListener('sales',e=>{const rows=JSON.parse(e.data);if(!rows.length)return;feed.innerHTML=rows.map(o=>`<a href="/admin/orders/${o.id}" class="flex items-center justify-between gap-4 p-4 hover:bg-slate-50"><div><div class="font-bold">${escapeHtml(o.customer)}</div><div class="text-xs text-slate-400">${escapeHtml(o.order_number)} · ${escapeHtml(o.program||'—')} · ${escapeHtml(o.partner||'Direct')}</div></div><div class="text-right"><div class="font-black">${escapeHtml(o.currency||'NGN')} ${Number(o.total).toLocaleString(undefined,{minimumFractionDigits:2})}</div><div class="text-xs text-slate-400">${new Date(o.created_at).toLocaleString()}</div></div></a>`).join('');status.textContent='Live';status.className='text-xs font-bold text-emerald-600'});source.onerror=()=>{status.textContent='Reconnecting…';status.className='text-xs font-bold text-amber-600';source.close();setTimeout(connect,10000)};}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}connect();
</script>
</x-app-layout>
