<?php

use App\Http\Controllers\Admin\AnalyticsController;
use App\Http\Controllers\Admin\SuperAdminAnalyticsController;
use App\Http\Controllers\Admin\BusinessController as AdminBusinessController;
use App\Http\Controllers\Admin\BusinessPayoutController as AdminBusinessPayoutController;
use App\Http\Controllers\Admin\CommissionController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PartnerController as AdminPartnerController;
use App\Http\Controllers\Admin\PartnerResolutionController;
use App\Http\Controllers\Admin\PayoutController as AdminPayoutController;
use App\Http\Controllers\Admin\PaymentController as AdminPaymentController;
use App\Http\Controllers\Admin\PaymentDisputeController as AdminPaymentDisputeController;
use App\Http\Controllers\Admin\RegistrationController as AdminRegistrationController;
use App\Http\Controllers\Admin\SettingsController as AdminSettingsController;
use App\Http\Controllers\Admin\UserManagementController as AdminUserManagementController;
use App\Http\Controllers\BusinessDashboardController;
use App\Http\Controllers\BusinessOnboardingController;
use App\Http\Controllers\BusinessPartnerApprovalController;
use App\Http\Controllers\BusinessPortalController;
use App\Http\Controllers\BusinessPayoutController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\CustomerDashboardController;
use App\Http\Controllers\ManualPaymentController;
use App\Http\Controllers\NetworkController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\PartnerDashboardController;
use App\Http\Controllers\PartnerMarketplaceController;
use App\Http\Controllers\PartnerReferralShowcaseController;
use App\Http\Controllers\PartnershipProgramController;
use App\Http\Controllers\PaymentDisputeController;
use App\Http\Controllers\PayoutController;
use App\Http\Controllers\ProductAccessController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductMarketplaceController;
use App\Http\Controllers\ProductShowController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SocialFollowController;
use App\Models\PartnershipProgram;
use App\Models\Product;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/partner/dashboard', [PartnerDashboardController::class, 'index'])->middleware('partner.approved')->name('partner.dashboard');
    Route::get('/partner/pending', fn () => view('partner.pending'))->name('partner.pending');
    Route::get('/partner/programs', [PartnerMarketplaceController::class, 'index'])->name('partner.marketplace.index');
    Route::get('/partner/programs/{program}', [PartnerMarketplaceController::class, 'show'])->name('partner.marketplace.show');
    Route::post('/partner/programs/{program}/join', [PartnerMarketplaceController::class, 'join'])->name('partner.marketplace.join');
    Route::get('/partner/payouts', [PayoutController::class, 'index'])->middleware('partner.approved')->name('partner.payouts.index');
    Route::post('/partner/payouts', [PayoutController::class, 'store'])->name('partner.payouts.store');
    Route::get('/business/pending', [BusinessOnboardingController::class, 'pending'])->name('business.pending');
    Route::middleware('business.approved')->group(function () {
        Route::get('/business/dashboard', [BusinessDashboardController::class, 'index'])->name('business.dashboard');
        Route::get('/business/payouts', [BusinessPayoutController::class, 'index'])->name('business.payouts.index');
        Route::post('/business/payouts', [BusinessPayoutController::class, 'store'])->name('business.payouts.store');
        Route::get('/business/programs', [BusinessPortalController::class, 'programs'])->name('business.programs.index');
        Route::get('/business/programs/{program}/edit', [BusinessPortalController::class, 'editProgram'])->name('business.programs.edit');
        Route::put('/business/programs/{program}', [BusinessPortalController::class, 'updateProgram'])->name('business.programs.update');
        Route::patch('/business/programs/{program}/toggle', [BusinessPortalController::class, 'toggleProgram'])->name('business.programs.toggle');
        Route::get('/business/products', [BusinessPortalController::class, 'products'])->name('business.products.index');
        Route::get('/business/products/create', [BusinessPortalController::class, 'createProduct'])->name('business.products.create');
        Route::post('/business/products', [BusinessPortalController::class, 'storeProduct'])->name('business.products.store');
        Route::get('/business/products/{product}/edit', [BusinessPortalController::class, 'editProduct'])->name('business.products.edit');
        Route::put('/business/products/{product}', [BusinessPortalController::class, 'updateProduct'])->name('business.products.update');
        Route::get('/business/affiliates', [BusinessPortalController::class, 'affiliates'])->name('business.affiliates.index');
        Route::get('/business/sales', [BusinessPortalController::class, 'sales'])->name('business.sales.index');
        Route::get('/business/commissions', [BusinessPortalController::class, 'commissions'])->name('business.commissions.index');
        Route::patch('/business/programs/{program}/partners/{partner}/approve', [BusinessPartnerApprovalController::class, 'approve'])->name('business.affiliates.approve');
        Route::patch('/business/programs/{program}/partners/{partner}/reject', [BusinessPartnerApprovalController::class, 'reject'])->name('business.affiliates.reject');
        Route::get('/business/onboarding/{step}', [BusinessOnboardingController::class, 'show'])->name('business.onboarding');
        Route::post('/business/onboarding/{step}', [BusinessOnboardingController::class, 'store'])->name('business.onboarding.store');
        Route::get('/business/social-follow/accounts', [SocialFollowController::class, 'accounts'])->name('business.social-follow.accounts');
        Route::post('/business/social-follow/accounts', [SocialFollowController::class, 'saveAccounts'])->name('business.social-follow.accounts.save');
        Route::get('/business/social-follow/campaigns', [SocialFollowController::class, 'campaigns'])->name('business.social-follow.campaigns.index');
        Route::get('/business/social-follow/campaigns/create', [SocialFollowController::class, 'create'])->name('business.social-follow.campaigns.create');
        Route::post('/business/social-follow/campaigns', [SocialFollowController::class, 'store'])->name('business.social-follow.campaigns.store');
        Route::get('/business/social-follow/campaigns/{campaign}/edit', [SocialFollowController::class, 'edit'])->name('business.social-follow.campaigns.edit');
        Route::put('/business/social-follow/campaigns/{campaign}', [SocialFollowController::class, 'update'])->name('business.social-follow.campaigns.update');
        Route::patch('/business/social-follow/campaigns/{campaign}/toggle', [SocialFollowController::class, 'toggle'])->name('business.social-follow.campaigns.toggle');
    });
    Route::get('/network', [NetworkController::class, 'index'])->middleware('role:super_admin|program_manager|partner')->name('network.index');
    Route::get('/customer/dashboard', [CustomerDashboardController::class, 'index'])->name('customer.dashboard');
    Route::get('/my-products/{item}', [ProductAccessController::class, 'show'])->name('customer.product-access');
});
Route::get('/business/start', [BusinessOnboardingController::class, 'start'])->name('business.start');
Route::middleware(['auth', 'role:super_admin'])->prefix('admin')->group(function () {
    Route::get('/', [AdminDashboardController::class, 'index'])->name('admin');
    Route::get('/realtime/sales', [AdminDashboardController::class, 'realtimeSales'])->name('admin.realtime.sales');
    Route::get('/users', [AdminUserManagementController::class, 'index'])->name('admin.users.index');
    Route::get('/users/{user}', [AdminUserManagementController::class, 'show'])->name('admin.users.show');
    Route::get('/users/{user}/partner-resolution', [PartnerResolutionController::class, 'show'])->name('admin.users.partner-resolution');
    Route::get('/users/{user}/edit', [AdminUserManagementController::class, 'edit'])->name('admin.users.edit');
    Route::put('/users/{user}', [AdminUserManagementController::class, 'update'])->name('admin.users.update');
    Route::patch('/users/{user}/verify-email', [AdminUserManagementController::class, 'verifyEmail'])->name('admin.users.verify-email');
    Route::patch('/users/{user}/repair-registration', [AdminUserManagementController::class, 'repairRegistration'])->name('admin.users.repair-registration');
    Route::delete('/users/{user}', [AdminUserManagementController::class, 'destroy'])->name('admin.users.destroy');
    Route::get('/analytics/businesses', [SuperAdminAnalyticsController::class, 'businesses'])->name('admin.analytics.businesses');
    Route::get('/analytics/businesses/{business}', [SuperAdminAnalyticsController::class, 'business'])->name('admin.analytics.business');
    Route::get('/analytics/businesses/{business}/partners/{programPartner}', [SuperAdminAnalyticsController::class, 'partner'])->name('admin.analytics.partner');
    Route::get('/analytics/{metric}', [AnalyticsController::class, 'show'])->name('admin.analytics.show');
    Route::get('/analytics/{metric}/export', [AnalyticsController::class, 'export'])->name('admin.analytics.export');
    Route::get('/settings', [AdminSettingsController::class, 'edit'])->name('admin.settings'); Route::put('/settings', [AdminSettingsController::class, 'update'])->name('admin.settings.update');
    Route::get('/payments', [AdminPaymentController::class, 'index'])->name('admin.payments.index'); Route::get('/payments/{payment}', [AdminPaymentController::class, 'show'])->name('admin.payments.show'); Route::get('/payments/{payment}/proof', [AdminPaymentController::class, 'proof'])->name('admin.payments.proof'); Route::patch('/payments/{payment}/confirm', [AdminPaymentController::class, 'confirm'])->name('admin.payments.confirm'); Route::patch('/payments/{payment}/reject', [AdminPaymentController::class, 'reject'])->name('admin.payments.reject');
    Route::get('/payment-disputes', [AdminPaymentDisputeController::class, 'index'])->name('admin.payment-disputes.index'); Route::patch('/payment-disputes/{dispute}/resolve', [AdminPaymentDisputeController::class, 'resolve'])->name('admin.payment-disputes.resolve');
    Route::get('/registrations', [AdminRegistrationController::class, 'index'])->name('admin.registrations.index'); Route::patch('/registrations/{user}/verify-email', [AdminRegistrationController::class, 'verifyEmail'])->name('admin.registrations.verify-email'); Route::post('/registrations/{user}/resend-verification', [AdminRegistrationController::class, 'resendVerification'])->name('admin.registrations.resend-verification'); Route::patch('/registrations/{user}/assign-business-role', [AdminRegistrationController::class, 'assignBusinessRole'])->name('admin.registrations.assign-business-role'); Route::patch('/registrations/{user}/approve', [AdminRegistrationController::class, 'approveBusiness'])->name('admin.registrations.approve'); Route::patch('/registrations/{user}/reject', [AdminRegistrationController::class, 'rejectBusiness'])->name('admin.registrations.reject'); Route::patch('/registrations/{user}/repair', [AdminRegistrationController::class, 'repair'])->name('admin.registrations.repair'); Route::delete('/registrations/{user}', [AdminRegistrationController::class, 'destroy'])->name('admin.registrations.destroy');
    Route::get('/businesses', [AdminBusinessController::class, 'index'])->name('admin.businesses.index'); Route::patch('/businesses/{business}/approve', [AdminBusinessController::class, 'approve'])->name('admin.businesses.approve'); Route::patch('/businesses/{business}/reject', [AdminBusinessController::class, 'reject'])->name('admin.businesses.reject');
    Route::get('/partners', [AdminPartnerController::class, 'index'])->name('admin.partners.index'); Route::patch('/partners/{partner}/approve', [AdminPartnerController::class, 'approve'])->name('admin.partners.approve'); Route::patch('/partners/{partner}/approve-for-business', [AdminPartnerController::class, 'approveForBusiness'])->name('admin.partners.approve-for-business'); Route::patch('/partners/{partner}/reject', [AdminPartnerController::class, 'reject'])->name('admin.partners.reject');
    Route::get('/programs', [PartnershipProgramController::class, 'index'])->name('admin.programs.index'); Route::get('/programs/create', [PartnershipProgramController::class, 'create'])->name('admin.programs.create'); Route::post('/programs', [PartnershipProgramController::class, 'store'])->name('admin.programs.store'); Route::get('/programs/{program}/edit', [PartnershipProgramController::class, 'edit'])->name('admin.programs.edit'); Route::put('/programs/{program}', [PartnershipProgramController::class, 'update'])->name('admin.programs.update');
    Route::get('/products', [ProductController::class, 'index'])->name('admin.products.index'); Route::get('/products/create', [ProductController::class, 'create'])->name('admin.products.create'); Route::post('/products', [ProductController::class, 'store'])->name('admin.products.store'); Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('admin.products.edit'); Route::put('/admin/products/{product}', [ProductController::class, 'update'])->name('admin.products.update');
    Route::get('/orders', [OrderController::class, 'index'])->name('admin.orders.index'); Route::get('/orders/{order}', [AdminDashboardController::class, 'index'])->name('admin.orders.placeholder');
});
Route::get('/partner/apply', [PartnerController::class, 'create'])->name('partner.apply'); Route::post('/partner/apply', [PartnerController::class, 'store'])->name('partner.apply.store');
Route::get('/partner/store/{partnerCode}', [PartnerReferralShowcaseController::class, 'show'])->name('partner.storefront');
Route::get('/marketplace', [ProductMarketplaceController::class, 'index'])->name('marketplace.products');
Route::get('/social-follow', fn () => view('social-follow.landing'))->name('social-follow.landing');
Route::get('/', function(){
    $programs = PartnershipProgram::query()->where('status','active')->with(['commissionRules'=>fn($query)=>$query->where('status',true)->orderBy('priority')->orderBy('level')])->latest()->limit(6)->get();
    $marketplaceProducts = Product::query()->where('status','active')->with(['owner','partnershipPrograms'=>fn($query)=>$query->where('status','active')->orderBy('name')])->withCount(['orderItems as paid_units_sold'=>fn($query)=>$query->whereHas('order',fn($order)=>$order->where('status','paid'))])->orderByDesc('paid_units_sold')->latest()->limit(6)->get();
    return view('home',compact('programs','marketplaceProducts'));
})->name('home');
Route::get('/dashboard', function(){ $user=request()->user(); if($user->hasRole('super_admin')) return redirect()->route('admin'); if($user->hasRole('program_manager')) return redirect()->route('business.dashboard'); if($user->hasRole('partner')) return redirect()->route('partner.dashboard'); if($user->hasRole('customer')) return redirect()->route('customer.dashboard'); return redirect()->route('home'); })->middleware(['auth','verified'])->name('dashboard');
Route::middleware('auth')->group(function(){ Route::get('/profile',[ProfileController::class,'edit'])->name('profile.edit'); Route::patch('/profile',[ProfileController::class,'update'])->name('profile.update'); Route::delete('/profile',[ProfileController::class,'destroy'])->name('profile.destroy'); });
Route::get('/product/{slug}',[ProductShowController::class,'show'])->name('product.show');
Route::post('/checkout',[CheckoutController::class,'create'])->name('checkout.create');
Route::get('/checkout/{product}',[CheckoutController::class,'show'])->name('checkout.show');
Route::get('/checkout/{product}/bank-transfer',[ManualPaymentController::class,'show'])->name('checkout.bank-transfer');
Route::post('/checkout/{product}/bank-transfer',[ManualPaymentController::class,'submit'])->name('checkout.bank-transfer.submit');
Route::post('/checkout/{product}/paystack',[CheckoutController::class,'paystack'])->name('checkout.paystack');
Route::post('/checkout/{order}/dispute',[PaymentDisputeController::class,'store'])->name('checkout.payment-dispute');
Route::post('/checkout/{orderId}/confirm-demo',[CheckoutController::class,'confirm'])->name('checkout.confirm');
Route::get('/checkout/paystack/callback',[CheckoutController::class,'paystackCallback'])->name('checkout.paystack.callback');
Route::post('/webhooks/paystack',[CheckoutController::class,'paystackWebhook'])->name('webhooks.paystack');
Route::get('/order/{orderId}/post-payment',[CheckoutController::class,'postPayment'])->name('order.post-payment');
Route::get('/follow/{slug}', [SocialFollowController::class, 'show'])->name('social-follow.show');
Route::post('/follow/{slug}/claim/{socialAccount}', [SocialFollowController::class, 'claim'])->name('social-follow.claim');
Route::post('/follow/{slug}/unlock', [SocialFollowController::class, 'unlock'])->name('social-follow.unlock');

require __DIR__.'/auth.php';
