<x-app-layout>
    <x-slot name="header"><div><h2 class="font-semibold text-xl text-gray-800 leading-tight">Platform Settings</h2><p class="text-sm text-gray-500 mt-1">Configure approvals, payouts, platform payments and customer support.</p></div></x-slot>
    <div class="py-8"><div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
        @if(session('success'))<div class="rounded-xl bg-emerald-50 text-emerald-700 px-4 py-3">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="rounded-xl bg-red-50 text-red-700 px-4 py-3"><ul class="list-disc ml-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <form method="POST" action="{{ route('admin.settings.update') }}" class="space-y-6">@csrf @method('PUT')
            <div class="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
                <h3 class="text-lg font-black text-gray-900">Partner applications</h3>
                <label class="mt-5 flex items-start gap-4 rounded-2xl border p-5 cursor-pointer hover:bg-slate-50"><input type="checkbox" name="partner_super_admin_approval_required" value="1" @checked($partnerSuperAdminApprovalRequired) class="mt-1 rounded text-violet-600"><span><b>Require Super Admin approval for partners</b><small class="block text-gray-500 mt-1">Email verification remains required.</small></span></label>
            </div>
            <div class="bg-white rounded-2xl border border-gray-100 shadow-sm p-6"><h3 class="text-lg font-black text-gray-900">Platform admin charge</h3><p class="text-sm text-gray-500 mt-1">Percentage retained by the platform from paid sales.</p><div class="mt-5 max-w-sm"><label class="block text-sm font-bold">Admin charge (%)</label><input type="number" min="0" max="100" step="0.01" name="admin_charge_percent" value="{{ old('admin_charge_percent', $adminChargePercent) }}" class="mt-2 w-full rounded-xl border-gray-300"></div></div>
            <div class="bg-white rounded-2xl border border-gray-100 shadow-sm p-6"><h3 class="text-lg font-black text-gray-900">Payout protection period</h3><div class="mt-5 max-w-sm"><label class="block text-sm font-bold">Hold period (days)</label><input type="number" min="0" max="90" name="payout_delay_days" value="{{ old('payout_delay_days', $payoutDelayDays) }}" class="mt-2 w-full rounded-xl border-gray-300"></div></div>
            <div class="bg-white rounded-2xl border border-gray-100 shadow-sm p-6"><h3 class="text-lg font-black text-gray-900">Manual bank transfer</h3><p class="text-sm text-gray-500 mt-1">These are the platform's receiving details. Admin verifies every manual payment before the order becomes paid.</p><div class="mt-5 grid gap-4 sm:grid-cols-3"><div><label class="text-sm font-bold">Bank name</label><input name="bank_name" value="{{ old('bank_name',$paymentSettings->bank_name) }}" class="mt-1 w-full rounded-xl border-gray-300"></div><div><label class="text-sm font-bold">Account name</label><input name="account_name" value="{{ old('account_name',$paymentSettings->account_name) }}" class="mt-1 w-full rounded-xl border-gray-300"></div><div><label class="text-sm font-bold">Account number</label><input name="account_number" value="{{ old('account_number',$paymentSettings->account_number) }}" class="mt-1 w-full rounded-xl border-gray-300"></div></div></div>
            <div class="bg-white rounded-2xl border border-gray-100 shadow-sm p-6"><h3 class="text-lg font-black text-gray-900">Customer care</h3><p class="text-sm text-gray-500 mt-1">Shown to buyers on payment pages for payment issues and disputes.</p><div class="mt-5 grid gap-4 sm:grid-cols-3"><div><label class="text-sm font-bold">Phone</label><input name="support_phone" value="{{ old('support_phone',$paymentSettings->support_phone) }}" class="mt-1 w-full rounded-xl border-gray-300"></div><div><label class="text-sm font-bold">WhatsApp</label><input name="support_whatsapp" value="{{ old('support_whatsapp',$paymentSettings->support_whatsapp) }}" class="mt-1 w-full rounded-xl border-gray-300"></div><div><label class="text-sm font-bold">Email</label><input type="email" name="support_email" value="{{ old('support_email',$paymentSettings->support_email) }}" class="mt-1 w-full rounded-xl border-gray-300"></div></div></div>
            <div class="flex justify-end"><button class="rounded-xl bg-violet-600 px-5 py-3 text-white font-bold">Save settings</button></div>
        </form>
        <div class="grid md:grid-cols-3 gap-4"><a href="{{ route('admin.payments.index') }}" class="bg-white border rounded-2xl p-5 hover:border-violet-200"><b>Payment verification</b><p class="text-sm text-gray-500 mt-1">Review manual bank-transfer proofs.</p></a><a href="{{ route('admin.partners.index') }}" class="bg-white border rounded-2xl p-5 hover:border-violet-200"><b>Partner applications</b><p class="text-sm text-gray-500 mt-1">Review partner approvals.</p></a><a href="{{ route('admin.payouts.index') }}" class="bg-white border rounded-2xl p-5 hover:border-violet-200"><b>Partner payouts</b><p class="text-sm text-gray-500 mt-1">Process commission payouts.</p></a></div>
    </div></div>
</x-app-layout>
