<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Product Marketplace · AIPM</title>
<link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">
<script src="https://cdn.tailwindcss.com"></script>
<style>html{scroll-behavior:smooth}.gradient{background:linear-gradient(135deg,#6d28d9,#c026d3)}.gradient-text{background:linear-gradient(90deg,#6d28d9,#c026d3);-webkit-background-clip:text;background-clip:text;color:transparent}</style>
</head>
<body class="bg-[#f8f8fb] text-gray-950 antialiased">
<nav class="sticky top-0 z-50 border-b border-gray-200/80 bg-white/95 backdrop-blur"><div class="mx-auto flex min-h-20 max-w-7xl items-center justify-between gap-4 px-5 lg:px-8"><a href="{{ route('home') }}" class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-gray-950 text-xs font-black text-white">AIPM</span><span class="hidden text-xl font-black sm:block">AI <span class="text-violet-600">Powered Marketing</span></span></a><div class="flex items-center gap-2"><a href="{{ route('home') }}" class="rounded-xl px-4 py-2.5 text-sm font-bold text-gray-600 hover:bg-gray-100">Home</a>@auth<a href="{{ route('dashboard') }}" class="rounded-xl bg-gray-950 px-4 py-2.5 text-sm font-black text-white">Dashboard</a>@else<a href="{{ route('login') }}" class="rounded-xl px-4 py-2.5 text-sm font-bold text-gray-600 hover:bg-gray-100">Log in</a>@endauth</div></div></nav>
<main>
<section class="gradient text-white"><div class="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-20"><div class="max-w-4xl"><span class="inline-flex rounded-full bg-white/15 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-violet-100">AIPM Product Marketplace</span><h1 class="mt-5 text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">Find the right product. Compare before you buy.</h1><p class="mt-5 max-w-3xl text-lg leading-8 text-violet-100">Explore every active product on AIPM — across all businesses and programs — then search, filter and sort using the information that matters to you.</p></div><form class="mt-8 grid gap-3 rounded-3xl bg-white p-3 shadow-2xl md:grid-cols-[1fr_auto]" method="GET" action="{{ route('marketplace.products') }}"><label class="sr-only" for="q">Search products</label><input id="q" name="q" value="{{ request('q') }}" placeholder="Search products, descriptions or SKU…" class="min-w-0 rounded-2xl border-0 bg-gray-50 px-5 py-4 text-gray-950 outline-none ring-1 ring-gray-200 focus:ring-2 focus:ring-violet-500"><button class="rounded-2xl bg-gray-950 px-7 py-4 font-black text-white hover:bg-violet-800">Search marketplace →</button></form></div></section>
<section class="mx-auto max-w-7xl px-5 py-8 lg:px-8"><div class="grid gap-4 lg:grid-cols-[280px_1fr] lg:items-start">
<aside class="rounded-3xl border border-gray-200 bg-white p-5 shadow-sm lg:sticky lg:top-28"><div class="flex items-center justify-between"><h2 class="text-lg font-black">Filter products</h2><a href="{{ route('marketplace.products') }}" class="text-xs font-bold text-violet-700">Clear all</a></div><form method="GET" action="{{ route('marketplace.products') }}" class="mt-5 space-y-5"><input type="hidden" name="q" value="{{ request('q') }}"><input type="hidden" name="sort" value="{{ $sort }}"><div><label class="text-xs font-black uppercase tracking-wide text-gray-500">Program</label><select name="program" class="mt-2 w-full rounded-xl border border-gray-200 bg-white px-3 py-3 text-sm font-semibold"><option value="">All programs</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected((string)request('program')===(string)$program->id)>{{ $program->name }}</option>@endforeach</select></div><div><label class="text-xs font-black uppercase tracking-wide text-gray-500">Currency</label><select name="currency" class="mt-2 w-full rounded-xl border border-gray-200 bg-white px-3 py-3 text-sm font-semibold"><option value="">All currencies</option>@foreach($currencies as $currency)<option value="{{ $currency }}" @selected(request('currency')===$currency)>{{ $currency }}</option>@endforeach</select></div><div><label class="text-xs font-black uppercase tracking-wide text-gray-500">Price range</label><div class="mt-2 grid grid-cols-2 gap-2"><input name="min_price" value="{{ request('min_price') }}" type="number" min="0" step="0.01" placeholder="Min" class="w-full rounded-xl border border-gray-200 px-3 py-3 text-sm"><input name="max_price" value="{{ request('max_price') }}" type="number" min="0" step="0.01" placeholder="Max" class="w-full rounded-xl border border-gray-200 px-3 py-3 text-sm"></div></div><button class="w-full rounded-xl bg-violet-600 px-4 py-3 font-black text-white hover:bg-violet-700">Apply filters</button></form><div class="mt-6 rounded-2xl bg-violet-50 p-4 text-sm leading-6 text-violet-900"><strong>What can I sort by?</strong><p class="mt-1">Newest, price, name and confirmed sales volume. Sales volume is based only on paid orders.</p></div></aside>
<div>
<div class="mb-5 flex flex-col gap-4 rounded-2xl border border-gray-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-bold text-gray-500">{{ $products->total() }} {{ Str::plural('product', $products->total()) }} available</p><p class="text-xs text-gray-400">Every active product is included, whether or not it belongs to a partnership program.</p></div><form method="GET" action="{{ route('marketplace.products') }}" class="flex items-center gap-2">@foreach(request()->except('sort','page') as $key=>$value) @if(is_scalar($value))<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif @endforeach<label for="sort" class="text-sm font-bold text-gray-500">Sort</label><select id="sort" name="sort" onchange="this.form.submit()" class="rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm font-bold"><option value="newest" @selected($sort==='newest')>Newest</option><option value="popular" @selected($sort==='popular')>Most purchased</option><option value="price_low" @selected($sort==='price_low')>Price: low to high</option><option value="price_high" @selected($sort==='price_high')>Price: high to low</option><option value="name" @selected($sort==='name')>Name: A–Z</option><option value="oldest" @selected($sort==='oldest')>Oldest</option></select></form></div>
@if($products->count())<div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@foreach($products as $product)<article class="group flex flex-col overflow-hidden rounded-3xl border border-gray-200 bg-white shadow-sm transition duration-200 hover:-translate-y-1 hover:shadow-xl"><a href="{{ route('product.show',$product->slug) }}" class="relative block aspect-[4/3] overflow-hidden bg-gradient-to-br from-violet-100 to-fuchsia-50">@if($product->featured_image)<img src="{{ Storage::url($product->featured_image) }}" alt="{{ $product->name }}" class="h-full w-full object-cover transition duration-300 group-hover:scale-105">@else<div class="grid h-full place-items-center text-5xl font-black text-violet-300">{{ strtoupper(substr($product->name,0,1)) }}</div>@endif<div class="absolute left-4 top-4 rounded-full bg-white/95 px-3 py-1.5 text-xs font-black text-emerald-700 shadow-sm">Active</div></a><div class="flex flex-1 flex-col p-5"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-wide text-violet-600">{{ $product->owner?->business_name ?: $product->owner?->name ?: 'AIPM seller' }}</p><h2 class="mt-1 text-xl font-black leading-tight">{{ $product->name }}</h2></div><div class="shrink-0 text-right"><p class="text-xs font-bold uppercase text-gray-400">Price</p><p class="text-lg font-black">{{ $product->currency }} {{ number_format((float)$product->price,2) }}</p></div></div><p class="mt-3 line-clamp-3 text-sm leading-6 text-gray-600">{{ $product->description ?: 'Explore this product to learn what it offers and whether it is right for you.' }}</p><div class="mt-4 flex flex-wrap gap-1.5">@forelse($product->partnershipPrograms as $program)<span class="rounded-full bg-violet-50 px-2.5 py-1 text-[11px] font-bold text-violet-700">{{ $program->name }}</span>@empty<span class="rounded-full bg-gray-100 px-2.5 py-1 text-[11px] font-bold text-gray-600">Direct product</span>@endforelse</div>
@if($product->partnershipPrograms->isNotEmpty())<div class="mt-4 rounded-2xl border border-emerald-100 bg-emerald-50 p-4"><div class="flex items-center justify-between gap-3"><p class="text-[11px] font-black uppercase tracking-wider text-emerald-700">Partner earning opportunity</p><span class="rounded-full bg-white px-2.5 py-1 text-[10px] font-black text-emerald-700">Earn per sale</span></div><div class="mt-3 space-y-2">@foreach($product->partnershipPrograms as $program)@php
$direct = $program->commissionRules->where('product_id', $product->id)->where('level', 1)->first() ?: $program->commissionRules->whereNull('product_id')->where('level', 1)->first();
$recruiter = $program->commissionRules->where('product_id', $product->id)->where('level', 2)->first() ?: $program->commissionRules->whereNull('product_id')->where('level', 2)->first();
$directAmount = $direct ? ($direct->commission_type === 'fixed' ? (float) $direct->value : ((float) $product->price * (float) $direct->value) / 100) : null;
if ($direct && $direct->maximum_amount !== null) { $directAmount = min($directAmount, (float) $direct->maximum_amount); }
$directLabel = $direct ? ($direct->commission_type === 'fixed' ? $product->currency.' '.number_format((float) $direct->value, 2) : rtrim(rtrim(number_format((float) $direct->value, 2), '0'), '.').'%') : null;
$recruiterLabel = $recruiter ? ($recruiter->commission_type === 'fixed' ? $product->currency.' '.number_format((float) $recruiter->value, 2) : rtrim(rtrim(number_format((float) $recruiter->value, 2), '0'), '.').'%') : null;
@endphp<div class="rounded-xl bg-white p-3"><div class="flex items-start justify-between gap-3"><p class="font-black text-slate-900">{{ $program->name }}</p>@if($directAmount !== null)<p class="text-right text-sm font-black text-emerald-700">{{ $product->currency }} {{ number_format($directAmount, 2) }}<span class="block text-[9px] font-bold uppercase tracking-wide text-gray-400">estimated direct earning</span></p>@endif</div><div class="mt-2 flex flex-wrap gap-2 text-[11px] font-bold">@if($directLabel)<span class="rounded-full bg-emerald-50 px-2.5 py-1 text-emerald-700">Direct {{ $directLabel }}</span>@else<span class="rounded-full bg-gray-100 px-2.5 py-1 text-gray-500">No direct commission set</span>@endif @if($recruiterLabel)<span class="rounded-full bg-violet-50 px-2.5 py-1 text-violet-700">Recruiter {{ $recruiterLabel }}</span>@endif @if($program->attribution_window_days)<span class="rounded-full bg-gray-100 px-2.5 py-1 text-gray-600">{{ $program->attribution_window_days }}-day attribution</span>@endif</div>@if($program->minimum_payout !== null)<p class="mt-2 text-[10px] font-semibold text-gray-500">Minimum payout: {{ $product->currency }} {{ number_format((float) $program->minimum_payout, 2) }}</p>@endif</div>@endforeach</div></div>@endif
<div class="mt-5 grid grid-cols-2 gap-2 border-y border-gray-100 py-4"><div><p class="text-[11px] font-black uppercase tracking-wide text-gray-400">Confirmed purchases</p><p class="mt-1 font-black">{{ number_format($product->paid_units_sold) }}</p></div><div><p class="text-[11px] font-black uppercase tracking-wide text-gray-400">Added</p><p class="mt-1 font-black">{{ $product->created_at->format('d M Y') }}</p></div></div><div class="mt-auto flex gap-2 pt-5"><a href="{{ route('product.show',$product->slug) }}" class="flex-1 rounded-xl border border-gray-200 px-4 py-3 text-center text-sm font-black text-gray-700 hover:border-violet-300 hover:text-violet-700">View details</a><a href="{{ route('checkout.show',$product->id) }}" class="flex-1 rounded-xl bg-gray-950 px-4 py-3 text-center text-sm font-black text-white hover:bg-violet-700">Buy now →</a></div></div></article>@endforeach</div><div class="mt-8">{{ $products->links() }}</div>@else<div class="rounded-3xl border border-dashed border-gray-300 bg-white p-14 text-center"><div class="text-5xl">🔎</div><h2 class="mt-4 text-2xl font-black">No products match those filters.</h2><p class="mt-2 text-gray-500">Try a broader search, remove a filter or browse every active product.</p><a href="{{ route('marketplace.products') }}" class="mt-6 inline-flex rounded-xl bg-gray-950 px-5 py-3 font-black text-white">Show all products</a></div>@endif
</div></div></section>
<section class="border-t border-gray-200 bg-white"><div class="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-sm text-gray-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span class="font-black text-gray-950">AIPM Product Marketplace</span><a href="{{ route('home') }}" class="font-bold text-violet-700">← Back to AIPM home</a></div></section>
</main></body></html>
