<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Turn customers into loyal social followers with LAMI AI Social Follow. Guide customers across YouTube, TikTok, Instagram and Facebook before unlocking your resource.">
    <meta property="og:title" content="Social Follow — Turn Customers Into Followers">
    <meta property="og:description" content="Grow your social audience while delivering your valuable content with LAMI AI Social Follow.">
    <title>Social Follow — Turn Customers Into Followers | LAMI AI</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config={theme:{extend:{colors:{tealx:{50:'#f0fdfa',100:'#ccfbf1',200:'#99f6e4',300:'#5eead4',400:'#2dd4bf',500:'#14b8a6',600:'#0d9488',700:'#0f766e',800:'#115e59',900:'#134e4a',950:'#042f2e'}},boxShadow:{tealglow:'0 25px 80px rgba(13,148,136,.18)'}}}};
    </script>
    <style>
        html{scroll-behavior:smooth}body{background:#f8fffe;color:#082f2e}.grid-bg{background-image:linear-gradient(rgba(13,148,136,.06) 1px,transparent 1px),linear-gradient(90deg,rgba(13,148,136,.06) 1px,transparent 1px);background-size:42px 42px}.hero-glow{background:radial-gradient(circle,rgba(45,212,191,.28),rgba(20,184,166,.08) 45%,transparent 70%)}.gradient-text{background:linear-gradient(90deg,#0f766e,#14b8a6,#2dd4bf);-webkit-background-clip:text;background-clip:text;color:transparent}.glass{background:rgba(255,255,255,.78);backdrop-filter:blur(18px)}
    </style>
</head>
<body class="font-sans antialiased">
<nav class="fixed inset-x-0 top-0 z-50 border-b border-teal-100/70 bg-white/85 backdrop-blur-xl">
 <div class="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
  <a href="{{ route('home') }}" class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-teal-950 text-lg font-black text-white shadow-lg">L</span><span class="text-xl font-black tracking-tight">LAMI <span class="text-teal-600">AI</span></span></a>
  <div class="hidden items-center gap-8 text-sm font-semibold text-teal-900/70 md:flex"><a href="#how" class="hover:text-teal-600">How it works</a><a href="#benefits" class="hover:text-teal-600">Benefits</a><a href="#platforms" class="hover:text-teal-600">Platforms</a></div>
  <a href="{{ route('register') }}" class="rounded-xl bg-teal-700 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-teal-700/20 transition hover:-translate-y-0.5 hover:bg-teal-800">Start Growing</a>
 </div>
</nav>
<main>
<section class="relative overflow-hidden pt-32 lg:pt-40"><div class="absolute inset-0 grid-bg"></div><div class="hero-glow absolute -right-32 top-4 h-[680px] w-[680px]"></div>
 <div class="relative mx-auto grid max-w-7xl items-center gap-14 px-5 pb-24 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-32">
  <div><div class="mb-7 inline-flex items-center gap-2 rounded-full border border-teal-200 bg-teal-50 px-4 py-2 text-xs font-black uppercase tracking-[.16em] text-teal-700"><span class="h-2 w-2 rounded-full bg-teal-500"></span> Social growth made simple</div>
   <h1 class="max-w-4xl text-5xl font-black leading-[.98] tracking-[-.045em] text-teal-950 sm:text-6xl lg:text-7xl">Turn every customer into a <span class="gradient-text">social follower.</span></h1>
   <p class="mt-7 max-w-2xl text-lg leading-8 text-teal-900/65 sm:text-xl">Give customers a reason to follow you on every platform. Let them complete simple social actions, watch their progress, and unlock your valuable resource when they reach your required score.</p>
   <div class="mt-9 flex flex-col gap-3 sm:flex-row"><a href="{{ route('register') }}" class="inline-flex items-center justify-center rounded-2xl bg-teal-700 px-7 py-4 font-black text-white shadow-xl shadow-teal-700/20 transition hover:-translate-y-1 hover:bg-teal-800">Start Growing Your Audience <span class="ml-2">→</span></a><a href="#how" class="inline-flex items-center justify-center rounded-2xl border border-teal-200 bg-white px-7 py-4 font-bold text-teal-900 hover:border-teal-400">See How It Works</a></div>
   <div class="mt-8 flex flex-wrap gap-x-7 gap-y-3 text-sm font-bold text-teal-900/55"><span>✓ No customer handles</span><span>✓ 4 major platforms</span><span>✓ Reward-gated access</span></div>
  </div>
  <div class="relative"><div class="absolute -inset-7 rounded-[2.5rem] bg-teal-400/15 blur-3xl"></div><div class="glass relative rounded-[2rem] border border-teal-100 p-4 shadow-2xl shadow-teal-950/10"><div class="rounded-[1.5rem] bg-teal-950 p-6 text-white sm:p-7"><div class="flex items-center justify-between"><div><p class="text-xs font-bold uppercase tracking-widest text-teal-300">Your campaign</p><p class="mt-1 text-xl font-black">Get the Free Guide</p></div><span class="rounded-full bg-teal-400/10 px-3 py-1.5 text-xs font-bold text-teal-300">3 / 4 complete</span></div><div class="mt-6 h-3 overflow-hidden rounded-full bg-white/10"><div class="h-full w-3/4 rounded-full bg-teal-400"></div></div><div class="mt-6 space-y-3">
   <div class="flex items-center gap-4 rounded-2xl bg-white/5 p-4"><span class="grid h-11 w-11 place-items-center rounded-xl bg-red-500/15 text-lg">▶</span><div class="flex-1"><p class="font-bold">YouTube</p><p class="text-xs text-teal-300">Subscribed</p></div><span class="text-teal-300">✓</span></div>
   <div class="flex items-center gap-4 rounded-2xl bg-white/5 p-4"><span class="grid h-11 w-11 place-items-center rounded-xl bg-pink-500/15 text-lg">◎</span><div class="flex-1"><p class="font-bold">Instagram</p><p class="text-xs text-teal-300">Following</p></div><span class="text-teal-300">✓</span></div>
   <div class="flex items-center gap-4 rounded-2xl bg-white/5 p-4"><span class="grid h-11 w-11 place-items-center rounded-xl bg-sky-500/15 text-lg">♪</span><div class="flex-1"><p class="font-bold">TikTok</p><p class="text-xs text-teal-300">Following</p></div><span class="text-teal-300">✓</span></div>
   <div class="flex items-center gap-4 rounded-2xl border border-dashed border-white/10 p-4 opacity-70"><span class="grid h-11 w-11 place-items-center rounded-xl bg-blue-500/15 text-lg">f</span><div class="flex-1"><p class="font-bold">Facebook</p><p class="text-xs text-teal-200/50">One more to unlock</p></div><span class="text-teal-200/40">○</span></div>
  </div><div class="mt-5 rounded-2xl bg-teal-500 p-4 text-center font-black text-teal-950">Unlock your resource →</div></div></div></div>
 </div>
</section>
<section class="border-y border-teal-100 bg-white"><div class="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-teal-100 sm:grid-cols-4"><div class="p-7 text-center"><p class="text-2xl font-black text-teal-950">YouTube</p><p class="mt-1 text-xs font-bold uppercase tracking-widest text-teal-900/45">Subscribe</p></div><div class="p-7 text-center"><p class="text-2xl font-black text-teal-950">TikTok</p><p class="mt-1 text-xs font-bold uppercase tracking-widest text-teal-900/45">Follow</p></div><div class="p-7 text-center"><p class="text-2xl font-black text-teal-950">Instagram</p><p class="mt-1 text-xs font-bold uppercase tracking-widest text-teal-900/45">Follow</p></div><div class="p-7 text-center"><p class="text-2xl font-black text-teal-950">Facebook</p><p class="mt-1 text-xs font-bold uppercase tracking-widest text-teal-900/45">Follow</p></div></div></section>
<section id="how" class="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div class="mx-auto max-w-2xl text-center"><span class="text-sm font-black uppercase tracking-[.2em] text-teal-600">How it works</span><h2 class="mt-4 text-4xl font-black tracking-tight text-teal-950 sm:text-5xl">A simple journey from customer to follower.</h2><p class="mt-5 text-lg leading-8 text-teal-900/60">Turn the moment someone wants your resource into an opportunity to grow your audience.</p></div><div class="mt-16 grid gap-6 md:grid-cols-4"><div class="rounded-3xl border border-teal-100 bg-white p-7 shadow-sm"><span class="grid h-12 w-12 place-items-center rounded-2xl bg-teal-50 text-xl font-black text-teal-700">01</span><h3 class="mt-6 text-xl font-black text-teal-950">Set your accounts</h3><p class="mt-2 leading-7 text-teal-900/55">Add your YouTube, TikTok, Instagram and Facebook profiles.</p></div><div class="rounded-3xl border border-teal-100 bg-white p-7 shadow-sm"><span class="grid h-12 w-12 place-items-center rounded-2xl bg-teal-50 text-xl font-black text-teal-700">02</span><h3 class="mt-6 text-xl font-black text-teal-950">Create your campaign</h3><p class="mt-2 leading-7 text-teal-900/55">Choose platforms, set your minimum score and add the resource you want to unlock.</p></div><div class="rounded-3xl border border-teal-100 bg-white p-7 shadow-sm"><span class="grid h-12 w-12 place-items-center rounded-2xl bg-teal-50 text-xl font-black text-teal-700">03</span><h3 class="mt-6 text-xl font-black text-teal-950">Customers follow</h3><p class="mt-2 leading-7 text-teal-900/55">Customers are guided through clear Follow or Subscribe actions without entering their handles.</p></div><div class="rounded-3xl border border-teal-100 bg-white p-7 shadow-sm"><span class="grid h-12 w-12 place-items-center rounded-2xl bg-teal-50 text-xl font-black text-teal-700">04</span><h3 class="mt-6 text-xl font-black text-teal-950">Unlock the reward</h3><p class="mt-2 leading-7 text-teal-900/55">Once the required score is reached, the resource becomes available.</p></div></div></section>
<section id="benefits" class="bg-teal-950 text-white"><div class="mx-auto grid max-w-7xl gap-14 px-5 py-24 lg:grid-cols-2 lg:px-8 lg:items-center"><div><span class="text-sm font-black uppercase tracking-[.2em] text-teal-300">Why businesses use it</span><h2 class="mt-4 text-4xl font-black tracking-tight sm:text-5xl">Stop choosing between giving value and growing your audience.</h2><p class="mt-6 text-lg leading-8 text-teal-100/60">Social Follow turns your valuable downloads, guides, offers and resources into a structured audience-growth experience.</p><a href="{{ route('register') }}" class="mt-8 inline-flex rounded-2xl bg-teal-400 px-6 py-4 font-black text-teal-950 hover:bg-teal-300">Create Your First Campaign →</a></div><div class="grid gap-4 sm:grid-cols-2"><div class="rounded-3xl border border-white/10 bg-white/5 p-7"><div class="text-3xl">🎯</div><h3 class="mt-5 text-xl font-black">Purposeful growth</h3><p class="mt-2 leading-7 text-teal-100/55">Every follow request is connected to something your customer already wants.</p></div><div class="rounded-3xl border border-white/10 bg-white/5 p-7"><div class="text-3xl">⚡</div><h3 class="mt-5 text-xl font-black">Less friction</h3><p class="mt-2 leading-7 text-teal-100/55">Clear platform buttons make the next action obvious.</p></div><div class="rounded-3xl border border-white/10 bg-white/5 p-7"><div class="text-3xl">📊</div><h3 class="mt-5 text-xl font-black">Visible progress</h3><p class="mt-2 leading-7 text-teal-100/55">Customers can see their score and exactly what remains.</p></div><div class="rounded-3xl border border-white/10 bg-white/5 p-7"><div class="text-3xl">🎁</div><h3 class="mt-5 text-xl font-black">Reward the action</h3><p class="mt-2 leading-7 text-teal-100/55">Use books, guides, downloads and other resources as your incentive.</p></div></div></div></section>
<section id="platforms" class="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div class="text-center"><span class="text-sm font-black uppercase tracking-[.2em] text-teal-600">One campaign. Multiple platforms.</span><h2 class="mt-4 text-4xl font-black tracking-tight text-teal-950 sm:text-5xl">Meet your audience where they already spend time.</h2></div><div class="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-3xl border border-teal-100 bg-white p-7 shadow-sm"><div class="grid h-14 w-14 place-items-center rounded-2xl bg-red-50 text-2xl">▶</div><h3 class="mt-6 text-xl font-black">YouTube</h3><p class="mt-2 text-teal-900/55">Send customers directly to your channel with an easy subscribe experience.</p></div><div class="rounded-3xl border border-teal-100 bg-white p-7 shadow-sm"><div class="grid h-14 w-14 place-items-center rounded-2xl bg-pink-50 text-2xl">◎</div><h3 class="mt-6 text-xl font-black">Instagram</h3><p class="mt-2 text-teal-900/55">Turn resource seekers into followers of your visual brand.</p></div><div class="rounded-3xl border border-teal-100 bg-white p-7 shadow-sm"><div class="grid h-14 w-14 place-items-center rounded-2xl bg-sky-50 text-2xl">♪</div><h3 class="mt-6 text-xl font-black">TikTok</h3><p class="mt-2 text-teal-900/55">Grow the audience that discovers you through short-form content.</p></div><div class="rounded-3xl border border-teal-100 bg-white p-7 shadow-sm"><div class="grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-2xl font-black">f</div><h3 class="mt-6 text-xl font-black">Facebook</h3><p class="mt-2 text-teal-900/55">Bring customers into your Facebook community and updates.</p></div></div></section>
<section class="px-5 pb-24 lg:px-8"><div class="mx-auto max-w-5xl overflow-hidden rounded-[2.5rem] bg-gradient-to-br from-teal-700 to-teal-950 px-7 py-16 text-center text-white shadow-2xl shadow-teal-900/20 sm:px-12"><span class="text-sm font-black uppercase tracking-[.2em] text-teal-200">Your audience is waiting</span><h2 class="mx-auto mt-4 max-w-3xl text-4xl font-black tracking-tight sm:text-5xl">Give people a reason to follow you today.</h2><p class="mx-auto mt-5 max-w-2xl text-lg leading-8 text-teal-100/70">Create a Social Follow campaign, connect your platforms and start turning valuable resources into long-term audience growth.</p><a href="{{ route('register') }}" class="mt-9 inline-flex rounded-2xl bg-white px-7 py-4 font-black text-teal-800 shadow-xl transition hover:-translate-y-1">Start Growing Your Social Audience →</a></div></section>
</main>
<footer class="border-t border-teal-100 bg-white"><div class="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm text-teal-900/50 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div class="font-bold text-teal-950">LAMI AI</div><div>Social Follow — built for businesses that want to grow.</div></div></footer>
</body>
</html>
