<x-app-layout>
<x-slot name="header"><div><h2 class="font-black text-xl text-gray-900">Create Marketing Campaign</h2><p class="text-sm text-gray-500 mt-1">Build a mobile-first lead funnel without writing code.</p></div></x-slot>
<div class="py-8" x-data="campaignBuilder()"><div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><form method="POST" action="{{ route('business.campaigns.store') }}" class="rounded-3xl border border-teal-100 bg-white p-6 shadow-sm sm:p-8 space-y-7">@csrf
<div><label class="text-sm font-black">Campaign name</label><input name="name" value="{{ old('name') }}" required placeholder="e.g. August Marketer Recruitment" class="mt-2 w-full rounded-xl border-slate-200 focus:border-teal-600 focus:ring-teal-600"></div>
<div><label class="text-sm font-black">Headline shown to leads</label><input name="headline" value="{{ old('headline') }}" required placeholder="Turn your network into income." class="mt-2 w-full rounded-xl border-slate-200 focus:border-teal-600 focus:ring-teal-600"></div>
<div><label class="text-sm font-black">Short description</label><textarea name="description" rows="3" placeholder="Tell people why they should complete this campaign." class="mt-2 w-full rounded-xl border-slate-200 focus:border-teal-600 focus:ring-teal-600">{{ old('description') }}</textarea></div>
<div class="rounded-3xl border border-teal-100 bg-teal-50/60 p-5 sm:p-6"><div class="flex items-center justify-between gap-4"><div><h3 class="font-black text-teal-950">Build your questions</h3><p class="mt-1 text-sm text-teal-900/70">Name, WhatsApp and email are always collected. Add, remove and reorder qualification questions below.</p></div><button type="button" @click="add()" class="rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-black text-white">+ Add question</button></div><div class="mt-5 space-y-3"><template x-for="(q,index) in questions" :key="q.id"><div class="rounded-2xl border border-teal-100 bg-white p-4"><div class="grid gap-3 sm:grid-cols-[1fr_170px_auto]"><input :name="`questions[${index}][label]`" x-model="q.label" placeholder="Question text" class="rounded-xl border-slate-200 focus:border-teal-600 focus:ring-teal-600" required><select :name="`questions[${index}][type]`" x-model="q.type" class="rounded-xl border-slate-200 focus:border-teal-600 focus:ring-teal-600"><option value="single_choice">Multiple choice</option><option value="text">Short text</option><option value="textarea">Long text</option><option value="email">Email</option><option value="phone">Phone</option></select><button type="button" @click="remove(index)" class="rounded-xl px-3 py-2 font-bold text-red-500 hover:bg-red-50">Remove</button></div><div x-show="q.type==='single_choice'" class="mt-3"><input :value="q.options.join(', ')" @input="q.options=$event.target.value.split(',').map(x=>x.trim()).filter(Boolean)" placeholder="Options separated by commas, e.g. Yes, No" class="w-full rounded-xl border-slate-200 focus:border-teal-600 focus:ring-teal-600"><template x-for="option in q.options"><input type="hidden" :name="`questions[${index}][options][]`" :value="option"></template><p class="mt-1 text-xs text-slate-400">Use commas to separate answer choices.</p></div><label class="mt-3 flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" :name="`questions[${index}][required]`" value="1" x-model="q.required" class="rounded border-slate-300 text-teal-700 focus:ring-teal-600"> Required</label></div></template></div></div>
<div><label class="text-sm font-black">Final redirect URL</label><p class="mt-1 text-xs text-slate-500">After submission, send the lead to WhatsApp, your website, checkout, booking page, group invite, etc.</p><input type="url" name="redirect_url" value="{{ old('redirect_url') }}" required placeholder="https://wa.me/234..." class="mt-2 w-full rounded-xl border-slate-200 focus:border-teal-600 focus:ring-teal-600"></div>
<div><label class="text-sm font-black">Status</label><select name="status" class="mt-2 w-full rounded-xl border-slate-200 focus:border-teal-600 focus:ring-teal-600"><option value="draft">Draft</option><option value="active">Active</option><option value="paused">Paused</option></select></div>
<div class="flex justify-end gap-3"><a href="{{ route('business.campaigns.index') }}" class="rounded-xl px-4 py-3 font-bold text-slate-500">Cancel</a><button class="rounded-xl bg-teal-700 px-6 py-3 font-black text-white hover:bg-teal-800">Create campaign</button></div>
</form></div></div>
<script>function campaignBuilder(){return{questions:@json($questions),add(){this.questions.push({id:'q_'+Date.now(),label:'',type:'text',required:false,options:[]})},remove(i){this.questions.splice(i,1)}}}</script>
</x-app-layout>
