<x-app-layout>
<x-slot name="header"><div><h2 class="font-black text-xl text-gray-900">Create Marketing Campaign</h2><p class="text-sm text-gray-500 mt-1">Create a six-step lead qualification funnel for your ads.</p></div></x-slot>
<div class="py-8"><div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8"><form method="POST" action="{{ route('business.campaigns.store') }}" class="rounded-3xl border border-teal-100 bg-white p-6 shadow-sm sm:p-8 space-y-6">@csrf
<div><label class="text-sm font-black">Campaign name</label><input name="name" value="{{ old('name') }}" required placeholder="e.g. Summer Marketer Recruitment" class="mt-2 w-full rounded-xl border-slate-200 focus:border-teal-600 focus:ring-teal-600">@error('name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div><label class="text-sm font-black">Headline shown to leads</label><input name="headline" value="{{ old('headline') }}" required placeholder="Turn your network into income." class="mt-2 w-full rounded-xl border-slate-200 focus:border-teal-600 focus:ring-teal-600"></div>
<div><label class="text-sm font-black">Short description</label><textarea name="description" rows="3" placeholder="Tell people why they should complete this application." class="mt-2 w-full rounded-xl border-slate-200 focus:border-teal-600 focus:ring-teal-600">{{ old('description') }}</textarea></div>
<div class="rounded-2xl bg-teal-50 p-5"><h3 class="font-black text-teal-900">Six-step form</h3><p class="mt-1 text-sm text-teal-800/70">The campaign automatically uses the six qualification questions: name, WhatsApp, email, online selling experience, what they sold, and sales performance.</p></div>
<div><label class="text-sm font-black">Final redirect URL</label><p class="mt-1 text-xs text-slate-500">After submitting, the lead is sent here. This can be WhatsApp, your website, booking page, group invite, checkout, etc.</p><input type="url" name="redirect_url" value="{{ old('redirect_url') }}" required placeholder="https://wa.me/234..." class="mt-2 w-full rounded-xl border-slate-200 focus:border-teal-600 focus:ring-teal-600">@error('redirect_url')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div><label class="text-sm font-black">Status</label><select name="status" class="mt-2 w-full rounded-xl border-slate-200 focus:border-teal-600 focus:ring-teal-600"><option value="draft">Draft</option><option value="active" {{ old('status') === 'active' ? 'selected' : '' }}>Active</option><option value="paused">Paused</option></select></div>
<div class="flex items-center justify-end gap-3"><a href="{{ route('business.campaigns.index') }}" class="rounded-xl px-4 py-3 font-bold text-slate-500">Cancel</a><button class="rounded-xl bg-teal-700 px-6 py-3 font-black text-white hover:bg-teal-800">Create campaign</button></div>
</form></div></div>
</x-app-layout>
