<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#070b1d">
    <link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">
    <link rel="alternate icon" href="{{ asset('favicon.svg') }}">
    <title>Partner Growth Hub · AIPM</title>
    @vite(['resources/css/app.css','resources/js/app.js'])
</head>
<body class="min-h-screen bg-slate-50 text-slate-900">
<div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8">
    @include('components.dashboard-payment-alert', ['count' => $totalPendingPaymentConfirmations ?? 0, 'role' => 'partner'])

    {{-- Persistent navigation: the partner should always know where they are and how to leave. --}}
    <nav class="sticky top-0 z-40 mb-6 rounded-2xl border border-slate-200 bg-white/95 p-2 shadow-sm backdrop-blur" aria-label="Partner navigation">
        <div class="flex flex-wrap items-center gap-2">
            <a href="{{ route('partner.dashboard') }}" class="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white" aria-current="page">Dashboard</a>
            <a href="{{ route('partner.marketplace.index') }}" class="rounded-xl px-4 py-2.5 text-sm font-bold text-slate-600 transition hover:bg-slate-100 hover:text-slate-950">Marketplace</a>
            <a href="{{ route('network.index') }}" class="rounded-xl px-4 py-2.5 text-sm font-bold text-slate-600 transition hover:bg-slate-100 hover:text-slate-950">My Network</a>
            <a href="{{ route('partner.payouts.index') }}" class="rounded-xl px-4 py-2.5 text-sm font-bold text-slate-600 transition hover:bg-slate-100 hover:text-slate-950">Earnings &amp; Payouts</a>
            @if($programStats->isNotEmpty())
                @php $navPartner = $programStats->first()['partner']; $navStoreUrl = route('partner.storefront', ['partnerCode' => $navPartner->partner_code]); @endphp
                <a href="{{ $navStoreUrl }}" target="_blank" rel="noopener noreferrer" class="rounded-xl px-4 py-2.5 text-sm font-bold text-slate-600 transition hover:bg-slate-100 hover:text-slate-950">My Store <span aria-hidden="true">↗</span></a>
            @endif
            <div class="ml-auto flex items-center gap-2">
                <button type="button" onclick="window.history.back()" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600 transition hover:bg-slate-50 hover:text-slate-950" title="Return to the page you came from">
                    ← Back
                </button>
                <a href="{{ route('home') }}" class="hidden rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600 transition hover:bg-slate-50 hover:text-slate-950 sm:inline-flex">Visit site</a>
                <form method="POST" action="{{ route('logout') }}" class="m-0">
                    @csrf
                    <button type="submit" class="rounded-xl bg-rose-50 px-4 py-2.5 text-sm font-black text-rose-700 transition hover:bg-rose-100">Log out</button>
                </form>
            </div>
        </div>
    </nav>

    <header class="mb-7 flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
        <div>
            <div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-violet-100 px-3 py-1 text-xs font-black uppercase tracking-[0.18em] text-violet-700">AIPM Partner Growth Hub</span><span class="text-xs font-bold text-slate-400">Sell • Recruit • Earn • Grow</span></div>
            <h1 class="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Welcome back, {{ auth()->user()->name }}.</h1>
            <p class="mt-2 max-w-3xl text-slate-600">Everything you need to turn your audience into customers, customers into referrals, and referrals into a growing partner network.</p>
        </div>
        <div class="flex flex-wrap gap-2">
            @if($programStats->isNotEmpty()) <a href="{{ $navStoreUrl }}" target="_blank" rel="noopener noreferrer" class="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white shadow-sm">🚀 My Store ↗</a> @endif
            <a href="{{ route('partner.marketplace.index') }}" class="rounded-xl bg-white px-4 py-3 text-sm font-black text-violet-700 shadow-sm ring-1 ring-violet-200">Browse Programs →</a>
            <a href="{{ route('network.index') }}" class="rounded-xl bg-violet-600 px-4 py-3 text-sm font-black text-white shadow-sm">👥 My Network</a>
            <a href="{{ route('partner.payouts.index') }}" class="rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white shadow-sm">💰 Payouts</a>
        </div>
    </header>

    <section class="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
        <a href="#sales-activity" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><p class="text-xs font-black uppercase tracking-wide text-slate-500">Total Sales</p><p class="mt-2 text-3xl font-black">₦{{ number_format($totalSalesAmount, 0) }}</p><p class="mt-1 text-xs text-slate-500">{{ $totalSales }} confirmed orders · View sales ↓</p></a>
        <a href="{{ route('partner.payouts.index') }}" class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><p class="text-xs font-black uppercase tracking-wide text-emerald-700">Available Earnings</p><p class="mt-2 text-3xl font-black text-emerald-700">₦{{ number_format($totalPending, 0) }}</p><p class="mt-1 text-xs text-emerald-700">Ready / eligible · Manage payout →</p></a>
        <a href="{{ route('partner.payouts.index') }}" class="rounded-2xl border border-blue-200 bg-blue-50 p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><p class="text-xs font-black uppercase tracking-wide text-blue-700">Lifetime Paid</p><p class="mt-2 text-3xl font-black text-blue-950">₦{{ number_format($totalPaid, 0) }}</p><p class="mt-1 text-xs text-blue-700">Already paid · View history →</p></a>
        <a href="{{ route('network.index') }}" class="rounded-2xl border border-violet-200 bg-violet-50 p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><p class="text-xs font-black uppercase tracking-wide text-violet-700">Partners Recruited</p><p class="mt-2 text-3xl font-black text-violet-950">{{ $totalRecruited }}</p><p class="mt-1 text-xs text-violet-700">People in your network · Open network →</p></a>
        <a href="#attention" class="rounded-2xl border border-amber-200 bg-amber-50 p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><p class="text-xs font-black uppercase tracking-wide text-amber-700">Needs Attention</p><p class="mt-2 text-3xl font-black text-amber-950">{{ $totalPendingPaymentConfirmations }}</p><p class="mt-1 text-xs text-amber-700">Orders awaiting confirmation · Review ↓</p></a>
    </section>

    <section class="mb-7 grid gap-5 lg:grid-cols-[1.55fr_.75fr]">
        <div class="overflow-hidden rounded-3xl bg-slate-950 p-7 text-white shadow-xl">
            <div class="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div class="max-w-2xl"><p class="text-xs font-black uppercase tracking-[0.2em] text-emerald-300">Your #1 sales asset</p><h2 class="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Stop explaining. Send people to your store.</h2><p class="mt-3 leading-7 text-slate-300">Your personal storefront gives prospects a simple path from discovery to product purchase while preserving your referral attribution.</p></div><div class="rounded-2xl border border-white/10 bg-white/5 p-5 text-center"><div class="text-4xl">🚀</div><p class="mt-2 text-xs font-bold uppercase tracking-wide text-slate-400">Ready to share</p></div></div>
            @if($programStats->isNotEmpty()) @php $firstPartner = $programStats->first()['partner']; $storeUrl = route('partner.storefront', ['partnerCode' => $firstPartner->partner_code]); @endphp
                <div class="mt-6 rounded-2xl border border-white/10 bg-white/5 p-4"><p class="mb-2 text-xs font-black uppercase tracking-wide text-slate-400">Your referral storefront link</p><div class="flex flex-col gap-3 sm:flex-row"><input id="store-link" readonly value="{{ $storeUrl }}" class="min-w-0 flex-1 rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-sm text-slate-200 outline-none"><button type="button" onclick="navigator.clipboard.writeText(document.getElementById('store-link').value);this.innerText='Copied ✓';setTimeout(()=>this.innerText='Copy Link',1600)" class="rounded-xl bg-emerald-400 px-5 py-3 text-sm font-black text-slate-950">Copy Link</button></div></div>
                <div class="mt-4 flex flex-wrap gap-3"><a href="{{ $storeUrl }}" target="_blank" rel="noopener noreferrer" class="rounded-xl bg-white px-5 py-3 text-sm font-black text-slate-950">View My Store ↗</a><span class="rounded-xl border border-white/10 px-5 py-3 text-sm font-bold text-slate-300">Opens in a new tab so you keep your dashboard open.</span></div>
            @else
                <div class="mt-5 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-slate-300">You don't have an active partner program yet. <a class="font-black text-emerald-300 underline" href="{{ route('partner.marketplace.index') }}">Browse available programs →</a></div>
            @endif
        </div>
        <div class="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm">
            <p class="text-xs font-black uppercase tracking-[0.18em] text-violet-600">Start here</p><h3 class="mt-2 text-2xl font-black">Your next 3 moves</h3>
            <div class="mt-5 space-y-4">
                <a href="{{ route('partner.marketplace.index') }}" class="flex gap-3 rounded-2xl p-2 transition hover:bg-slate-50"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-violet-100 text-sm font-black text-violet-700">1</span><div><p class="font-black">Choose what to promote →</p><p class="text-sm text-slate-500">Browse programs and understand the offer.</p></div></a>
                <a href="{{ route('network.index') }}" class="flex gap-3 rounded-2xl p-2 transition hover:bg-slate-50"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-sm font-black text-emerald-700">2</span><div><p class="font-black">Build your network →</p><p class="text-sm text-slate-500">Invite people who can genuinely sell or refer.</p></div></a>
                <a href="{{ route('partner.payouts.index') }}" class="flex gap-3 rounded-2xl p-2 transition hover:bg-slate-50"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-amber-100 text-sm font-black text-amber-700">3</span><div><p class="font-black">Track your money →</p><p class="text-sm text-slate-500">See earnings, payout status and payment history.</p></div></a>
            </div>
        </div>
    </section>

    <section class="mb-7 grid gap-5 lg:grid-cols-3">
        <div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-[0.18em] text-violet-600">Recruitment engine</p><h2 class="mt-1 text-2xl font-black">Build a network that keeps working</h2><p class="mt-2 text-sm text-slate-500">Your dashboard tracks both direct sales and the value created by the network you recruit.</p></div><a href="{{ route('network.index') }}" class="whitespace-nowrap rounded-xl bg-violet-50 px-4 py-2 text-sm font-black text-violet-700">Open Network →</a></div><div class="mt-6 grid gap-4 sm:grid-cols-3"><a href="#earnings" class="rounded-2xl bg-slate-50 p-5 transition hover:shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-slate-500">Direct commission</p><p class="mt-2 text-2xl font-black">₦{{ number_format((float)$programStats->sum('direct_commission'), 0) }}</p><p class="mt-1 text-xs text-slate-500">From your direct sales · Details ↓</p></a><a href="{{ route('network.index') }}" class="rounded-2xl bg-violet-50 p-5 transition hover:shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-violet-600">Network commission</p><p class="mt-2 text-2xl font-black text-violet-950">₦{{ number_format((float)$programStats->sum('recruiter_commission'), 0) }}</p><p class="mt-1 text-xs text-violet-600">From deeper levels · Open network →</p></a><a href="{{ route('network.index') }}" class="rounded-2xl bg-emerald-50 p-5 transition hover:shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-emerald-700">Network size</p><p class="mt-2 text-2xl font-black text-emerald-950">{{ $totalRecruited }}</p><p class="mt-1 text-xs text-emerald-700">Partners recruited · View network →</p></a></div><div class="mt-6 rounded-2xl border border-dashed border-violet-200 bg-violet-50/50 p-5"><p class="font-black text-violet-950">Recruiting tip</p><p class="mt-1 text-sm leading-6 text-violet-900">Don't pitch "join my network" first. Lead with the opportunity: <strong>learn what the product does, show the earning opportunity, then invite them to start.</strong></p><a href="{{ route('network.index') }}" class="mt-3 inline-flex rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-black text-white">Go to My Network →</a></div></div>
        <div class="rounded-3xl bg-gradient-to-br from-violet-600 to-indigo-700 p-6 text-white shadow-lg"><p class="text-xs font-black uppercase tracking-[0.18em] text-violet-200">Recruitment script</p><h3 class="mt-2 text-2xl font-black">Copy. Paste. Start conversations.</h3><div class="mt-5 rounded-2xl bg-white/10 p-4 text-sm leading-6 text-violet-50">"I found a practical way to earn from products I already know how to recommend. You don't need to build a product yourself. Want me to show you how it works?"</div><button type="button" onclick="navigator.clipboard.writeText('I found a practical way to earn from products I already know how to recommend. You don\'t need to build a product yourself. Want me to show you how it works?');this.innerText='Script copied ✓';setTimeout(()=>this.innerText='Copy recruitment script',1600)" class="mt-4 w-full rounded-xl bg-white px-4 py-3 text-sm font-black text-violet-700">Copy recruitment script</button></div>
    </section>

    <section class="mb-7 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        <div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-black uppercase tracking-[0.18em] text-violet-600">Product intelligence</p><h2 class="mt-1 text-2xl font-black">Know which products deserve your attention</h2><p class="mt-2 max-w-3xl text-sm text-slate-500">Don't treat every product equally. Use sales volume, revenue, commission, average order value and your referral conversion rate to decide what to promote first.</p></div><div class="rounded-xl bg-violet-50 px-4 py-3 text-right"><p class="text-xs font-bold uppercase tracking-wide text-violet-600">Best seller</p><p class="font-black text-violet-950">{{ optional(optional($topProducts->first())['product'] ?? null)->name ?? 'No sales yet' }}</p></div></div>
        <div class="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="rounded-2xl bg-slate-50 p-5"><p class="text-xs font-black uppercase tracking-wide text-slate-500">Referral clicks</p><p class="mt-2 text-2xl font-black">{{ number_format($programStats->sum('clicks')) }}</p><p class="mt-1 text-xs text-slate-500">People reaching your referral traffic</p></div><div class="rounded-2xl bg-emerald-50 p-5"><p class="text-xs font-black uppercase tracking-wide text-emerald-700">Click → sale</p><p class="mt-2 text-2xl font-black text-emerald-950">{{ number_format($programStats->sum('clicks') > 0 ? ($totalSales / $programStats->sum('clicks')) * 100 : 0, 1) }}%</p><p class="mt-1 text-xs text-emerald-700">Your overall referral conversion</p></div><div class="rounded-2xl bg-blue-50 p-5"><p class="text-xs font-black uppercase tracking-wide text-blue-700">Average sale</p><p class="mt-2 text-2xl font-black text-blue-950">₦{{ number_format($programStats->sum('paid_orders') > 0 ? $totalSalesAmount / $programStats->sum('paid_orders') : 0, 0) }}</p><p class="mt-1 text-xs text-blue-700">Average confirmed order value</p></div><div class="rounded-2xl bg-amber-50 p-5"><p class="text-xs font-black uppercase tracking-wide text-amber-700">Best product</p><p class="mt-2 text-lg font-black text-amber-950">{{ optional(optional($topProducts->first())['product'] ?? null)->name ?? '—' }}</p><p class="mt-1 text-xs text-amber-700">Highest confirmed product revenue</p></div></div>

        <div class="mt-6 grid gap-5 lg:grid-cols-2">
            @forelse($topProducts as $item)
                @php $product = $item['product']; $rules = $item['rules']; $metadata = is_array($product->metadata) ? $product->metadata : []; $description = trim(strip_tags((string)$product->description)); @endphp
                <article class="rounded-3xl border {{ $item['is_top_seller'] ? 'border-emerald-300 ring-2 ring-emerald-100' : 'border-slate-200' }} p-6 shadow-sm">
                    <div class="flex items-start justify-between gap-4"><div><div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-black uppercase tracking-wide text-slate-600">{{ ucfirst($product->status) }}</span>@if($item['is_top_seller'])<span class="rounded-full bg-emerald-100 px-2.5 py-1 text-[11px] font-black uppercase tracking-wide text-emerald-700">🔥 Top seller</span>@endif</div><h3 class="mt-3 text-2xl font-black">{{ $product->name }}</h3><p class="mt-1 text-xs font-semibold text-slate-400">SKU: {{ $product->sku ?: 'Not set' }}</p></div><div class="text-right"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Price</p><p class="text-xl font-black">{{ $product->currency }} {{ number_format((float)$product->price, 0) }}</p></div></div>
                    @if($description)<p class="mt-4 text-sm leading-6 text-slate-600">{{ \Illuminate\Support\Str::limit($description, 280) }}</p>@endif
                    <div class="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><div class="rounded-xl bg-slate-50 p-3"><p class="text-[11px] font-bold uppercase text-slate-400">Units</p><p class="mt-1 text-lg font-black">{{ number_format($item['units_sold']) }}</p></div><div class="rounded-xl bg-slate-50 p-3"><p class="text-[11px] font-bold uppercase text-slate-400">Orders</p><p class="mt-1 text-lg font-black">{{ number_format($item['orders_count']) }}</p></div><div class="rounded-xl bg-slate-50 p-3"><p class="text-[11px] font-bold uppercase text-slate-400">Revenue</p><p class="mt-1 text-lg font-black">₦{{ number_format($item['revenue'],0) }}</p></div><div class="rounded-xl bg-emerald-50 p-3"><p class="text-[11px] font-bold uppercase text-emerald-600">Your commission</p><p class="mt-1 text-lg font-black text-emerald-800">₦{{ number_format($item['commission'],0) }}</p></div></div>
                    <div class="mt-4 grid gap-3 sm:grid-cols-2"><div class="rounded-xl border border-slate-100 p-4"><p class="text-xs font-bold text-slate-500">Average order value</p><p class="mt-1 font-black">₦{{ number_format($item['average_order_value'],0) }}</p><p class="mt-2 text-xs text-slate-400">Last sale: {{ $item['last_sale_at'] ? $item['last_sale_at']->format('d M Y') : 'No sale yet' }}</p></div><div class="rounded-xl border border-slate-100 p-4"><p class="text-xs font-bold text-slate-500">Why promote it?</p><p class="mt-1 text-sm font-semibold text-slate-700">{{ $item['orders_count'] > 0 ? 'It already converts for you. Prioritize this product in your content and follow-ups.' : 'No confirmed sales yet. Test it with a small, targeted audience before investing heavily.' }}</p></div></div>
                    <details class="mt-4 rounded-2xl bg-slate-50 p-4"><summary class="cursor-pointer text-sm font-black text-slate-700">Product details & earning rules</summary><div class="mt-4 space-y-4 text-sm"><div><p class="font-black">Full description</p><p class="mt-1 whitespace-pre-line leading-6 text-slate-600">{{ $product->description ?: 'No product description provided.' }}</p></div><div><p class="font-black">Commission rules</p>@if(count($rules))<div class="mt-2 space-y-2">@foreach($rules as $rule)<div class="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-white p-3"><span>{{ ucfirst($rule['event']) }} · Level {{ $rule['level'] }}</span><strong>{{ $rule['type'] }}: {{ $rule['value'] }}@if($rule['maximum_amount']) (max ₦{{ number_format($rule['maximum_amount'],0) }})@endif</strong></div>@endforeach</div>@else<p class="mt-1 text-slate-500">No product-specific commission rule is configured; check the program rules.</p>@endif</div>@if(count($metadata))<div><p class="font-black">Additional product information</p><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach($metadata as $key => $value) @if(is_scalar($value))<div class="rounded-xl bg-white p-3"><p class="text-[11px] font-bold uppercase tracking-wide text-slate-400">{{ str_replace('_',' ',ucwords($key)) }}</p><p class="mt-1 break-words font-semibold text-slate-700">{{ $value }}</p></div>@endif @endforeach</div></div>@endif</div></details>
                </article>
            @empty
                <div class="rounded-2xl bg-slate-50 p-8 text-center text-slate-500 lg:col-span-2">No products are currently attached to your active partnership programs. <a href="{{ route('partner.marketplace.index') }}" class="font-black text-violet-700 underline">Browse programs →</a></div>
            @endforelse
        </div>

        <div class="mt-6 rounded-2xl border border-dashed border-violet-200 bg-violet-50 p-5"><p class="font-black text-violet-950">How to use this intelligence</p><div class="mt-2 grid gap-3 text-sm leading-6 text-violet-900 md:grid-cols-3"><p><strong>1. Push winners:</strong> Products with sales and commission are your safest starting point.</p><p><strong>2. Improve weak products:</strong> If a product has clicks but no sales, change your message, audience or follow-up.</p><p><strong>3. Protect your time:</strong> Prioritize products with strong revenue and commission rather than promoting everything equally.</p></div><a href="{{ route('partner.marketplace.index') }}" class="mt-4 inline-flex rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-black text-white">Explore more programs →</a></div>
    </section>

    <section id="sales-activity" class="mb-7 scroll-mt-24 grid gap-5 lg:grid-cols-[1.25fr_.75fr]">
        <div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-[0.18em] text-violet-600">Sales activity</p><h2 class="mt-1 text-2xl font-black">Recent confirmed sales</h2></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">{{ $totalSales }} total</span></div><div class="mt-5 overflow-x-auto"><table class="min-w-full text-left text-sm"><thead><tr class="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><th class="px-3 py-3">Order</th><th class="px-3 py-3">Customer</th><th class="px-3 py-3">Sale</th><th class="px-3 py-3">Your earning</th><th class="px-3 py-3">Status</th></tr></thead><tbody>@php $recentSales = $programStats->flatMap(fn($s) => $s['sale_breakdown']->map(fn($sale) => ['sale'=>$sale,'program'=>$s['program']]))->sortByDesc(fn($x) => optional($x['sale']['order'])->created_at)->take(8); @endphp @forelse($recentSales as $item) @php $sale=$item['sale']; $order=$sale['order']; @endphp<tr class="border-b border-slate-100"><td class="px-3 py-4 font-bold">{{ $order->order_number }}</td><td class="px-3 py-4">{{ $order->customer_name }}</td><td class="px-3 py-4 font-semibold">₦{{ number_format($sale['sale_value'],0) }}</td><td class="px-3 py-4 font-black text-emerald-700">₦{{ number_format($sale['partner_earnings'],0) }}</td><td class="px-3 py-4"><span class="rounded-full bg-emerald-50 px-2 py-1 text-xs font-black text-emerald-700">{{ ucfirst($order->status) }}</span></td></tr>@empty<tr><td colspan="5" class="px-3 py-8 text-center text-slate-500">Your first confirmed sale will appear here.</td></tr>@endforelse</tbody></table></div><a href="{{ route('partner.payouts.index') }}" class="mt-5 inline-flex rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">View earnings &amp; payouts →</a></div>
        <div id="attention" class="scroll-mt-24 rounded-3xl border border-amber-200 bg-amber-50 p-6 shadow-sm"><p class="text-xs font-black uppercase tracking-[0.18em] text-amber-700">Conversion checklist</p><h3 class="mt-2 text-2xl font-black text-amber-950">Before you share</h3><div class="mt-5 space-y-4 text-sm text-amber-950"><div class="flex gap-3"><span>✓</span><p>Know the <strong>problem</strong> your product solves.</p></div><div class="flex gap-3"><span>✓</span><p>Show the prospect the <strong>outcome</strong>, not just features.</p></div><div class="flex gap-3"><span>✓</span><p>Send your <strong>storefront link</strong> instead of a long explanation.</p></div><div class="flex gap-3"><span>✓</span><p>Follow up with people who showed interest.</p></div><div class="flex gap-3"><span>✓</span><p>Recruit people who can genuinely <strong>sell or refer</strong>.</p></div></div><a href="{{ $programStats->isNotEmpty() ? $storeUrl : route('partner.marketplace.index') }}" target="_blank" rel="noopener noreferrer" class="mt-5 inline-flex rounded-xl bg-amber-600 px-4 py-2.5 text-sm font-black text-white">{{ $programStats->isNotEmpty() ? 'Open my store ↗' : 'Find a program →' }}</a></div>
    </section>

    <section id="earnings" class="mb-7 scroll-mt-24 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-black uppercase tracking-[0.18em] text-violet-600">Earnings command center</p><h2 class="mt-1 text-2xl font-black">Understand where your money comes from</h2></div><a href="{{ route('partner.payouts.index') }}" class="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">Manage payouts →</a></div><div class="mt-5 grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 p-5"><p class="text-xs font-bold uppercase tracking-wide text-slate-500">Direct sales earnings</p><p class="mt-2 text-2xl font-black">₦{{ number_format((float)$programStats->sum('direct_commission'),0) }}</p><p class="mt-1 text-xs text-slate-500">Commission from your direct customer sales.</p></div><div class="rounded-2xl border border-violet-200 bg-violet-50 p-5"><p class="text-xs font-bold uppercase tracking-wide text-violet-700">Recruiter earnings</p><p class="mt-2 text-2xl font-black text-violet-950">₦{{ number_format((float)$programStats->sum('recruiter_commission'),0) }}</p><p class="mt-1 text-xs text-violet-700">Commission from eligible deeper-level network activity.</p></div><div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p class="text-xs font-bold uppercase tracking-wide text-emerald-700">Total commission generated</p><p class="mt-2 text-2xl font-black text-emerald-950">₦{{ number_format((float)$programStats->sum('total_commissions'),0) }}</p><p class="mt-1 text-xs text-emerald-700">Across your confirmed sales.</p></div></div></section>

    <footer class="border-t border-slate-200 pb-8 pt-6 text-center text-xs font-semibold text-slate-400"><div class="flex flex-wrap items-center justify-center gap-x-4 gap-y-2"><a href="{{ route('partner.dashboard') }}" class="hover:text-slate-700">Dashboard</a><span aria-hidden="true">•</span><a href="{{ route('partner.marketplace.index') }}" class="hover:text-slate-700">Marketplace</a><span aria-hidden="true">•</span><a href="{{ route('network.index') }}" class="hover:text-slate-700">Network</a><span aria-hidden="true">•</span><a href="{{ route('partner.payouts.index') }}" class="hover:text-slate-700">Payouts</a><span aria-hidden="true">•</span><button type="button" onclick="window.history.back()" class="hover:text-slate-700">Back</button><span aria-hidden="true">•</span><form method="POST" action="{{ route('logout') }}" class="inline m-0">@csrf<button type="submit" class="hover:text-rose-700">Log out</button></form></div><p class="mt-3">AIPM Partner Growth Hub · Your goal is simple: more conversations → more customers → more partners → more earnings.</p></footer>
</div>
</body>
</html>
