<x-app-layout>
<x-slot name="header"><div><h2 class="font-black text-xl text-gray-900">Edit Social Follow Campaign</h2><p class="text-sm text-gray-500 mt-1">Update the accounts/groups, required options, score requirement or reward.</p></div></x-slot>
<div class="py-8"><div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><form method="POST" action="{{route('business.social-follow.campaigns.update',$campaign)}}" class="space-y-6">@csrf @method('PUT')
<div class="rounded-3xl border bg-white p-6 shadow-sm space-y-5"><div><label class="text-sm font-black">Campaign name</label><input name="name" value="{{old('name',$campaign->name)}}" required class="mt-2 w-full rounded-xl border-slate-200"></div><div><label class="text-sm font-black">Headline</label><input name="headline" value="{{old('headline',$campaign->headline)}}" required class="mt-2 w-full rounded-xl border-slate-200"></div><div><label class="text-sm font-black">Description</label><textarea name="description" rows="3" class="mt-2 w-full rounded-xl border-slate-200">{{old('description',$campaign->description)}}</textarea></div></div>
<div class="rounded-3xl border bg-white p-6 shadow-sm"><h3 class="text-lg font-black">Socials and groups</h3><p class="mt-1 text-sm text-slate-500">Mark any selected option as Required. Required options must be completed before the resource unlocks.</p><div class="mt-5 grid gap-3">@foreach($accounts as $account)<div class="flex flex-col gap-3 rounded-2xl border p-4 sm:flex-row sm:items-center"><label class="flex min-w-0 flex-1 cursor-pointer items-center gap-4"><input type="checkbox" name="social_accounts[]" value="{{$account->id}}" @checked($campaign->socialAccounts->contains('id',$account->id)) class="rounded border-slate-300 text-teal-700 focus:ring-teal-600"><span class="min-w-0"><span class="block font-black capitalize">{{str_replace('_',' ', $account->platform)}}</span><span class="block truncate text-xs text-slate-500">{{$account->handle ?: $account->profile_url}}</span></span></label><label class="flex items-center gap-2 text-sm font-black text-teal-700 sm:w-32"><input type="checkbox" name="required_social_accounts[]" value="{{$account->id}}" @checked($campaign->socialAccounts->contains(fn($selected) => $selected->id === $account->id && (bool)$selected->pivot->is_required)) class="rounded border-slate-300 text-teal-700 focus:ring-teal-600"> Required</label></div>@endforeach</div></div>
<div class="rounded-3xl border bg-white p-6 shadow-sm space-y-5"><div><label class="text-sm font-black">Minimum score</label><input type="number" min="1" name="minimum_score" value="{{old('minimum_score',$campaign->minimum_score)}}" required class="mt-2 w-full rounded-xl border-slate-200"><p class="mt-1 text-xs text-slate-500">The visitor must reach this score and complete every Required option.</p></div><div><label class="text-sm font-black">Resource title</label><input name="resource_title" value="{{old('resource_title',$campaign->resource_title)}}" required class="mt-2 w-full rounded-xl border-slate-200"></div><div><label class="text-sm font-black">Resource URL</label><input type="url" name="resource_url" value="{{old('resource_url',$campaign->resource_url)}}" required class="mt-2 w-full rounded-xl border-slate-200"></div><div><label class="text-sm font-black">Unlock button text</label><input name="resource_button_text" value="{{old('resource_button_text',$campaign->resource_button_text)}}" required class="mt-2 w-full rounded-xl border-slate-200"></div></div>
<div class="rounded-2xl bg-slate-50 p-4 text-sm"><b>Campaign URL:</b> <a target="_blank" class="font-bold text-teal-700" href="{{route('social-follow.show',$campaign->slug)}}">{{route('social-follow.show',$campaign->slug)}}</a></div><div class="flex justify-end gap-3"><a href="{{route('business.social-follow.campaigns.index')}}" class="rounded-xl px-5 py-3 font-bold text-slate-500">Cancel</a><button class="rounded-xl bg-teal-700 px-6 py-3 font-black text-white">Save changes</button></div>
</form></div></div>
</x-app-layout>
