<x-app-layout>
<x-slot name="header"><div><p class="text-xs font-black uppercase tracking-widest text-violet-600">User 360°</p><h2 class="font-black text-2xl text-gray-900">Edit account</h2><p class="text-sm text-gray-500 mt-1">Correct profile, registration and manageable role information. Super Admin accounts are protected.</p></div></x-slot>
<div class="py-6 bg-slate-50 min-h-screen"><div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">@include('admin.partials.command-nav')
@if($errors->any())<div class="mb-4 rounded-2xl bg-rose-50 border border-rose-200 p-4 text-rose-700"><ul class="list-disc list-inside text-sm">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('admin.users.update',$user) }}" class="space-y-5">@csrf @method('PUT')
<section class="rounded-3xl border bg-white p-6 shadow-sm"><p class="text-xs font-black uppercase tracking-widest text-violet-600">Core account</p><h3 class="text-xl font-black mt-1">Identity & registration</h3><div class="grid gap-4 md:grid-cols-2 mt-5"><label class="block"><span class="text-sm font-bold">Name</span><input name="name" value="{{ old('name',$user->name) }}" required class="mt-1 w-full rounded-xl border-slate-200"></label><label class="block"><span class="text-sm font-bold">Email</span><input type="email" name="email" value="{{ old('email',$user->email) }}" required class="mt-1 w-full rounded-xl border-slate-200"></label><label class="block"><span class="text-sm font-bold">Registration type</span><select name="registration_type" class="mt-1 w-full rounded-xl border-slate-200"><option value="customer" @selected(old('registration_type',$user->registration_type)==='customer')>Customer</option><option value="business" @selected(old('registration_type',$user->registration_type)==='business')>Business</option></select></label><label class="block"><span class="text-sm font-bold">Business name</span><input name="business_name" value="{{ old('business_name',$user->business_name) }}" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="block"><span class="text-sm font-bold">Business phone</span><input name="business_phone" value="{{ old('business_phone',$user->business_phone) }}" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="block"><span class="text-sm font-bold">Business industry</span><input name="business_industry" value="{{ old('business_industry',$user->business_industry) }}" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="block md:col-span-2"><span class="text-sm font-bold">Business website</span><input name="business_website" value="{{ old('business_website',$user->business_website) }}" class="mt-1 w-full rounded-xl border-slate-200"></label></div></section>
<section class="rounded-3xl border bg-white p-6 shadow-sm"><p class="text-xs font-black uppercase tracking-widest text-emerald-600">Roles</p><h3 class="text-xl font-black mt-1">Manage account modes</h3><p class="text-sm text-slate-500 mt-1">Super Admin cannot be granted, removed or edited from this screen.</p><div class="mt-5 grid gap-3 sm:grid-cols-3">@foreach(['customer'=>'Customer','partner'=>'Partner / Affiliate','program_manager'=>'Business / Program Manager'] as $value=>$label)<label class="rounded-2xl border p-4 flex gap-3 items-start"><input type="checkbox" name="roles[]" value="{{ $value }}" @checked(in_array($value,old('roles',$user->roles->pluck('name')->all()),true)) class="mt-1"><span><b class="block">{{ $label }}</b><small class="text-slate-500">Allow this account mode.</small></span></label>@endforeach</div></section>
<div class="flex flex-wrap justify-end gap-3"><a href="{{ route('admin.users.show',$user) }}" class="rounded-xl border bg-white px-5 py-3 font-black text-slate-600">Cancel</a><button class="rounded-xl bg-violet-600 text-white px-5 py-3 font-black">Save account changes</button></div>
</form></div></div></x-app-layout>
