<x-app-layout>
<x-slot name="header"><div><p class="text-xs font-black uppercase tracking-widest text-violet-600">Platform control</p><h2 class="font-black text-2xl text-gray-900">Users & Account Resolution</h2><p class="text-sm text-gray-500 mt-1">One control center for finding users, diagnosing account problems and resolving registration issues.</p></div></x-slot>
<div class="py-6 bg-slate-50 min-h-screen"><div class="max-w-[1600px] mx-auto px-4 sm:px-6 lg:px-8">
@include('admin.partials.command-nav')
@if(session('success'))<div class="mb-4 rounded-2xl bg-emerald-50 border border-emerald-200 p-4 text-emerald-700 font-semibold">{{ session('success') }}</div>@endif
@if(session('error'))<div class="mb-4 rounded-2xl bg-rose-50 border border-rose-200 p-4 text-rose-700 font-semibold">{{ session('error') }}</div>@endif
<div class="grid grid-cols-2 lg:grid-cols-5 gap-3 mb-5">
<div class="rounded-2xl bg-white border p-4"><span class="text-xs text-slate-400">All users</span><b class="block text-2xl mt-1">{{ number_format($stats['total']) }}</b></div>
<a href="{{ route('admin.users.index',['needs_attention'=>1]) }}" class="rounded-2xl bg-amber-50 border border-amber-200 p-4 hover:shadow-sm"><span class="text-xs text-amber-700">Needs attention</span><b class="block text-2xl mt-1 text-amber-900">{{ number_format($stats['unverified'] + $stats['business_issues']) }}</b></a>
<div class="rounded-2xl bg-blue-50 border border-blue-200 p-4"><span class="text-xs text-blue-700">Customers</span><b class="block text-2xl mt-1 text-blue-950">{{ number_format($stats['customers']) }}</b></div>
<div class="rounded-2xl bg-violet-50 border border-violet-200 p-4"><span class="text-xs text-violet-700">Partners</span><b class="block text-2xl mt-1 text-violet-950">{{ number_format($stats['partners']) }}</b></div>
<div class="rounded-2xl bg-rose-50 border border-rose-200 p-4"><span class="text-xs text-rose-700">Business issues</span><b class="block text-2xl mt-1 text-rose-950">{{ number_format($stats['business_issues']) }}</b></div>
</div>
<div class="rounded-3xl bg-slate-950 text-white p-6 mb-5 shadow-lg"><div class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-[0.18em] text-emerald-300">User 360° control tower</p><h3 class="text-2xl font-black mt-1">When a user has a problem, start here.</h3><p class="text-slate-300 text-sm mt-2 max-w-3xl">Search the account, see its registration state, orders, payments and partnership activity, then edit or repair what is safe to change.</p></div><a href="{{ route('admin.registrations.index') }}" class="rounded-xl bg-white text-slate-950 px-4 py-3 text-sm font-black">Registration Recovery →</a></div></div>
<form method="GET" class="rounded-2xl border bg-white p-4 mb-5"><div class="grid gap-3 md:grid-cols-4"><input name="q" value="{{ request('q') }}" placeholder="Name, email, business or phone" class="rounded-xl border-slate-200"><select name="role" class="rounded-xl border-slate-200"><option value="">All roles</option>@foreach(['customer','partner','program_manager'] as $role)<option value="{{ $role }}" @selected(request('role')===$role)>{{ ucfirst(str_replace('_',' ',$role)) }}</option>@endforeach</select><select name="registration_type" class="rounded-xl border-slate-200"><option value="">All registration types</option><option value="customer" @selected(request('registration_type')==='customer')>Customer</option><option value="business" @selected(request('registration_type')==='business')>Business</option></select><div class="flex gap-2"><button class="flex-1 rounded-xl bg-violet-600 text-white font-black">Search</button><a href="{{ route('admin.users.index') }}" class="rounded-xl border px-4 py-2 font-black text-slate-600">Reset</a></div></div><label class="mt-3 inline-flex items-center gap-2 text-sm font-bold text-slate-600"><input type="checkbox" name="needs_attention" value="1" @checked(request()->boolean('needs_attention'))> Show only accounts needing attention</label></form>
<div class="rounded-2xl border bg-white shadow-sm overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4 text-left">User</th><th class="p-4 text-left">Roles</th><th class="p-4">Registration</th><th class="p-4">Verification</th><th class="p-4">Account health</th><th class="p-4 text-left">Actions</th></tr></thead><tbody class="divide-y">@forelse($users as $user)<tr class="hover:bg-violet-50/40 align-top"><td class="p-4"><div class="font-black">{{ $user->business_name ?: $user->name }}</div><div class="text-xs text-slate-400">#{{ $user->id }} · {{ $user->email }}</div><div class="text-xs text-slate-400">Joined {{ $user->created_at?->format('d M Y') }}</div></td><td class="p-4"><div class="flex flex-wrap gap-1">@foreach($user->roles as $role)<span class="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold">{{ str_replace('_',' ',ucfirst($role->name)) }}</span>@endforeach</div></td><td class="p-4 text-center"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $user->registration_type==='business' ? 'bg-violet-100 text-violet-700' : 'bg-blue-100 text-blue-700' }}">{{ ucfirst($user->registration_type) }}</span></td><td class="p-4 text-center"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $user->email_verified_at ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700' }}">{{ $user->email_verified_at ? 'Verified' : 'Unverified' }}</span></td><td class="p-4 text-center">@if(!$user->email_verified_at || ($user->registration_type==='business' && (!$user->business_super_admin_approved_at || !$user->business_name || !$user->business_phone)))<span class="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-black text-amber-800">Needs attention</span>@else<span class="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-black text-emerald-700">Healthy</span>@endif</td><td class="p-4"><div class="flex flex-wrap gap-2"><a href="{{ route('admin.users.show',$user) }}" class="rounded-lg bg-slate-900 text-white px-3 py-2 text-xs font-black">Open User 360°</a><a href="{{ route('admin.users.edit',$user) }}" class="rounded-lg bg-violet-50 border border-violet-200 text-violet-700 px-3 py-2 text-xs font-black">Edit</a></div></td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-slate-400">No users match these filters.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $users->links() }}</div></div>
</div></div></x-app-layout>
