@extends('layouts.admin')

@section('content')
<div class="container-fluid py-4">
    <div class="d-flex justify-content-between align-items-start mb-4">
        <div><a href="{{ route('admin.analytics.businesses') }}" class="btn btn-sm btn-outline-secondary mb-3">← All Businesses</a><h1 class="h3 mb-1">{{ $business->business_name ?: $business->name }}</h1><div class="text-muted">{{ $business->name }} · {{ $business->email }} · {{ $business->business_phone ?: 'No phone' }}</div></div>
        <div><span class="badge {{ $business->business_super_admin_approved_at ? 'bg-success' : ($business->business_rejected_at ? 'bg-danger' : 'bg-warning text-dark') }}">{{ $business->business_super_admin_approved_at ? 'Approved' : ($business->business_rejected_at ? 'Rejected' : 'Pending approval') }}</span><div class="small text-muted mt-2">Joined {{ $business->created_at?->format('d M Y H:i') }}</div></div>
    </div>

    <div class="row g-3 mb-4">
        @foreach([['Gross Sales','₦'.number_format($stats['gross_sales'],2),''],['Net Revenue','₦'.number_format($stats['net_revenue'],2),''],['Commissions','₦'.number_format($stats['commissions'],2),''],['Paid Orders',$stats['paid_orders'],''],['Customers',$stats['customers'],''],['Partners',$stats['partners'],''],['Programs',$stats['programs'],''],['Avg. Order','₦'.number_format($stats['average_order'],2),'']] as $stat)
        <div class="col-6 col-md-3"><div class="card shadow-sm h-100"><div class="card-body"><small class="text-muted">{{ $stat[0] }}</small><div class="h5 mb-0 mt-1">{{ $stat[1] }}</div></div></div></div>
        @endforeach
    </div>

    <div class="row g-3 mb-4">
        <div class="col-lg-8"><div class="card shadow-sm h-100"><div class="card-header"><strong>Business profile</strong></div><div class="card-body"><div class="row g-3"><div class="col-md-6"><small class="text-muted">Business name</small><div>{{ $business->business_name ?: $business->name }}</div></div><div class="col-md-6"><small class="text-muted">Account email</small><div>{{ $business->email }}</div></div><div class="col-md-6"><small class="text-muted">Industry</small><div>{{ $business->business_industry ?: 'Not provided' }}</div></div><div class="col-md-6"><small class="text-muted">Website</small><div>{{ $business->business_website ?: 'Not provided' }}</div></div><div class="col-md-6"><small class="text-muted">Phone</small><div>{{ $business->business_phone ?: 'Not provided' }}</div></div><div class="col-md-6"><small class="text-muted">Email verified</small><div>{{ $business->email_verified_at ? 'Yes · '.$business->email_verified_at->format('d M Y') : 'No' }}</div></div></div></div></div></div>
        <div class="col-lg-4"><div class="card shadow-sm h-100"><div class="card-header"><strong>Financial position</strong></div><div class="card-body"><div class="d-flex justify-content-between py-2"><span>Gross sales</span><strong>₦{{ number_format($stats['gross_sales'],2) }}</strong></div><div class="d-flex justify-content-between py-2"><span>Commissions</span><strong>₦{{ number_format($stats['commissions'],2) }}</strong></div><div class="d-flex justify-content-between py-2"><span>Net revenue</span><strong>₦{{ number_format($stats['net_revenue'],2) }}</strong></div><div class="d-flex justify-content-between py-2"><span>Refunded</span><strong>₦{{ number_format($stats['refunded'],2) }}</strong></div><div class="d-flex justify-content-between py-2"><span>Payouts requested</span><strong>₦{{ number_format($stats['payouts_requested'],2) }}</strong></div><div class="d-flex justify-content-between py-2"><span>Payouts paid</span><strong>₦{{ number_format($stats['payouts_paid'],2) }}</strong></div></div></div></div>
    </div>

    <div class="card shadow-sm mb-4"><div class="card-header d-flex justify-content-between"><strong>Programs & performance</strong><span class="text-muted">{{ $programs->count() }} programs</span></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Program</th><th>Status</th><th>Partners</th><th>Products</th><th>Orders</th><th>Commission rules</th></tr></thead><tbody>@forelse($programs as $program)<tr><td><strong>{{ $program->name }}</strong><br><small class="text-muted">{{ $program->slug }}</small></td><td>{{ ucfirst($program->status) }}</td><td>{{ $program->partners_count }}</td><td>{{ $program->products_count }}</td><td>{{ $program->orders_count }}</td><td>{{ $program->commissionRules->count() }}</td></tr>@empty<tr><td colspan="6" class="text-center py-4">No programs.</td></tr>@endforelse</tbody></table></div></div>

    <div class="card shadow-sm mb-4"><div class="card-header"><strong>All partners under this business</strong> <span class="text-muted">({{ $partners->count() }})</span></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Partner</th><th>Program</th><th>Recruited by</th><th>Recruits</th><th>Status</th><th></th></tr></thead><tbody>@forelse($partners as $partner)<tr><td><strong>{{ $partner->user->name }}</strong><br><small class="text-muted">{{ $partner->user->email }}</small></td><td>{{ $partner->program->name }}</td><td>{{ $partner->parentPartner?->user?->name ?? 'Direct / none' }}</td><td>{{ $partner->children_count }}</td><td>{{ ucfirst($partner->status ?? 'active') }}</td><td><a href="{{ route('admin.analytics.partner', [$business, $partner]) }}" class="btn btn-sm btn-outline-primary">Full details</a></td></tr>@empty<tr><td colspan="6" class="text-center py-4">No partners.</td></tr>@endforelse</tbody></table></div></div>

    <div class="row g-3 mb-4"><div class="col-lg-7"><div class="card shadow-sm h-100"><div class="card-header"><strong>Customers</strong> <span class="text-muted">({{ $customers->count() }})</span></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Customer</th><th>Email</th><th>Joined</th></tr></thead><tbody>@forelse($customers->take(30) as $customer)<tr><td>{{ $customer->name }}</td><td>{{ $customer->email }}</td><td>{{ $customer->created_at?->format('d M Y') }}</td></tr>@empty<tr><td colspan="3" class="text-center py-3">No registered customers yet.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-lg-5"><div class="card shadow-sm h-100"><div class="card-header"><strong>Recent activity</strong></div><div class="card-body p-0"><div class="list-group list-group-flush">@forelse($recentActivity as $activity)<div class="list-group-item"><strong>{{ $activity['label'] }}</strong><div class="small">{{ $activity['description'] }}</div><small class="text-muted">{{ $activity['date']?->format('d M Y H:i') }}</small></div>@empty<div class="p-3 text-muted">No activity.</div>@endforelse</div></div></div></div></div>

    <div class="card shadow-sm mb-4"><div class="card-header"><strong>Sales / orders</strong> <span class="text-muted">({{ $orders->count() }})</span></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Order</th><th>Customer</th><th>Partner</th><th>Program</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>@forelse($orders->take(100) as $order)<tr><td>{{ $order->order_number }}</td><td>{{ $order->customer?->name ?? $order->customer_name ?? $order->customer_email }}</td><td>{{ $order->partner?->user?->name ?? 'Direct' }}</td><td>{{ $order->program?->name }}</td><td>₦{{ number_format($order->total,2) }}</td><td>{{ ucfirst($order->status) }}</td><td>{{ $order->created_at?->format('d M Y H:i') }}</td></tr>@empty<tr><td colspan="7" class="text-center py-4">No orders.</td></tr>@endforelse</tbody></table></div></div>

    <div class="row g-3"><div class="col-lg-7"><div class="card shadow-sm"><div class="card-header"><strong>Commission trail</strong></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Recipient</th><th>Program</th><th>Level</th><th>Amount</th><th>Status</th></tr></thead><tbody>@forelse($commissions->take(50) as $commission)<tr><td>{{ $commission->partner?->user?->name ?? '—' }}</td><td>{{ $commission->program?->name }}</td><td>{{ $commission->level ?? $commission->rule?->level ?? '—' }}</td><td>₦{{ number_format($commission->amount,2) }}</td><td>{{ ucfirst($commission->status) }}</td></tr>@empty<tr><td colspan="5" class="text-center py-3">No commissions.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-lg-5"><div class="card shadow-sm"><div class="card-header"><strong>Business payouts</strong></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Reference</th><th>Amount</th><th>Status</th></tr></thead><tbody>@forelse($payouts as $payout)<tr><td>{{ $payout->reference ?: '—' }}</td><td>₦{{ number_format($payout->amount,2) }}</td><td>{{ ucfirst($payout->status) }}</td></tr>@empty<tr><td colspan="3" class="text-center py-3">No payouts.</td></tr>@endforelse</tbody></table></div></div></div></div>
</div>
@endsection
