<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-widest text-violet-600">Super Admin Analytics</p><h2 class="font-semibold text-xl text-gray-800 leading-tight">{{ $title }}</h2><p class="text-sm text-gray-500 mt-1">Filtered, paginated platform analytics.</p></div><div class="flex gap-2"><a href="{{ route('admin.analytics.export', array_merge(['metric'=>$metric], request()->only('from','to'))) }}" class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white">Export CSV</a><a href="{{ route('admin') }}" class="rounded-xl border px-4 py-2 text-sm font-bold">← Dashboard</a></div></div></x-slot>
    <div class="py-8"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
        <form method="GET" class="bg-white rounded-2xl border shadow-sm p-4 flex flex-wrap items-end gap-3"><div><label class="block text-xs font-black uppercase text-gray-400">From</label><input type="date" name="from" value="{{ request('from') }}" class="mt-1 rounded-xl border-gray-200"></div><div><label class="block text-xs font-black uppercase text-gray-400">To</label><input type="date" name="to" value="{{ request('to') }}" class="mt-1 rounded-xl border-gray-200"></div><button class="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-black text-white">Apply</button><a href="{{ route('admin.analytics.show',$metric) }}" class="rounded-xl border px-4 py-2.5 text-sm font-bold">All time</a></form>
        <div class="grid grid-cols-2 md:grid-cols-4 gap-4">@foreach([['Gross sales',$stats['gross_sales']],['Net revenue',$stats['net_revenue']],['Commissions',$stats['commission_total']],['Completed orders',$stats['orders']]] as $card)<div class="bg-white rounded-2xl border border-gray-100 shadow-sm p-5"><p class="text-xs font-bold uppercase tracking-wide text-gray-500">{{ $card[0] }}</p><p class="mt-2 text-2xl font-black">{{ $card[0] === 'Completed orders' ? number_format($card[1]) : '₦'.number_format($card[1],2) }}</p></div>@endforeach</div>
        <div class="bg-white rounded-2xl border shadow-sm p-5"><div class="flex justify-between"><div><h3 class="font-black">Performance trend</h3><p class="text-sm text-gray-500">Sales and commissions by day.</p></div><span class="text-xs text-gray-400">{{ count($series) }} days</span></div><canvas id="analyticsChart" height="100" class="mt-4 w-full"></canvas></div>

        @if(in_array($metric, ['sales', 'orders'], true))
            <div class="bg-white rounded-2xl border shadow-sm overflow-hidden"><div class="p-5 border-b"><h3 class="font-black text-lg">Completed order detail</h3><p class="text-sm text-gray-500">Paginated to keep large datasets safe.</p></div><div class="divide-y">@forelse($orders as $order)<div class="p-6"><div class="flex flex-col md:flex-row md:items-start md:justify-between gap-4"><div><p class="font-mono text-xs text-gray-500">{{ $order->order_number }}</p><h4 class="mt-1 font-black">{{ $order->customer?->name ?? $order->customer_name ?? 'Guest customer' }}</h4><p class="text-sm text-gray-500">{{ $order->customer?->email ?? $order->customer_email ?? '—' }}</p><p class="text-xs text-gray-500 mt-2">Partner: <b>{{ $order->partner?->user?->name ?? 'Direct / none' }}</b> · Program: {{ $order->program?->name ?? '—' }}</p></div><div class="text-right"><p class="text-xl font-black">{{ $order->currency }} {{ number_format((float)$order->total, 2) }}</p><p class="text-xs text-gray-500">{{ ($order->paid_at ?? $order->created_at)?->format('M d, Y H:i') }}</p></div></div><div class="grid md:grid-cols-3 gap-3 mt-5"><div class="rounded-xl bg-gray-50 p-4"><p class="text-xs text-gray-500">Customer paid</p><p class="font-black mt-1">₦{{ number_format((float)$order->total, 2) }}</p></div><div class="rounded-xl bg-amber-50 p-4"><p class="text-xs text-amber-700">Commissions</p><p class="font-black text-amber-950 mt-1">₦{{ number_format((float)$order->commissions->whereNotIn('status',['reversed','cancelled'])->sum('commission_amount'), 2) }}</p></div><div class="rounded-xl bg-blue-50 p-4"><p class="text-xs text-blue-700">Operational net</p><p class="font-black text-blue-950 mt-1">₦{{ number_format(max(0,(float)$order->total-(float)$order->commissions->whereNotIn('status',['reversed','cancelled'])->sum('commission_amount')), 2) }}</p></div></div></div>@empty<div class="p-12 text-center text-gray-500">No completed sales yet.</div>@endforelse</div><div class="p-4 border-t">{{ $orders->links() }}</div></div>
        @elseif($metric === 'partners')
            <div class="grid lg:grid-cols-2 gap-6"><div class="bg-white rounded-2xl border shadow-sm overflow-hidden"><div class="p-5 border-b"><h3 class="font-black">Partners</h3></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50"><tr><th class="text-left p-4">Partner</th><th class="text-left p-4">Program</th><th class="text-left p-4">Status</th><th class="text-left p-4">Recruited</th><th class="text-left p-4">Earnings</th></tr></thead><tbody class="divide-y">@forelse($partnersList as $partner)<tr><td class="p-4 font-semibold">{{ $partner->user?->name ?? '—' }}</td><td class="p-4">{{ $partner->program?->name ?? '—' }}</td><td class="p-4">{{ ucfirst($partner->status) }}</td><td class="p-4">{{ $partner->child_partners_count }}</td><td class="p-4 font-black">₦{{ number_format((float)($partner->earnings ?? 0),2) }}</td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-gray-500">No partners yet.</td></tr>@endforelse</tbody></table></div><div class="p-4 border-t">{{ $partnersList->links() }}</div></div><div class="bg-white rounded-2xl border shadow-sm overflow-hidden"><div class="p-5 border-b"><h3 class="font-black">Partner recruitment</h3></div><div class="divide-y">@forelse($recruits as $recruit)<div class="p-4"><p class="font-bold">{{ $recruit->parentPartner?->user?->name ?? 'Partner' }} recruited {{ $recruit->user?->name ?? 'new partner' }}</p><p class="text-xs text-gray-500 mt-1">{{ $recruit->program?->name ?? '—' }} · {{ $recruit->created_at?->diffForHumans() }}</p></div>@empty<div class="p-8 text-center text-gray-500">No recruitment activity.</div>@endforelse</div></div></div>
        @elseif($metric === 'programs')
            <div class="bg-white rounded-2xl border shadow-sm overflow-hidden"><div class="p-5 border-b"><h3 class="font-black">Program performance</h3></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50"><tr><th class="text-left p-4">Program</th><th class="p-4">Status</th><th class="p-4">Partners</th><th class="p-4">Products</th><th class="p-4">Orders</th><th class="p-4">Sales</th></tr></thead><tbody class="divide-y">@forelse($programList as $program)<tr><td class="p-4 font-bold">{{ $program->name }}</td><td class="p-4">{{ ucfirst($program->status) }}</td><td class="p-4 text-center">{{ $program->partners_count }}</td><td class="p-4 text-center">{{ $program->products_count }}</td><td class="p-4 text-center">{{ $program->orders_count }}</td><td class="p-4 font-black">₦{{ number_format((float)($program->sales ?? 0),2) }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-gray-500">No programs yet.</td></tr>@endforelse</tbody></table></div><div class="p-4 border-t">{{ $programList->links() }}</div></div>
        @elseif($metric === 'products')
            <div class="bg-white rounded-2xl border shadow-sm overflow-hidden"><div class="p-5 border-b"><h3 class="font-black">Product catalogue</h3><p class="text-sm text-gray-500">Product listing is paginated; sales aggregation belongs to order analytics.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50"><tr><th class="text-left p-4">Product</th><th class="text-left p-4">Owner</th><th class="text-left p-4">Status</th><th class="text-left p-4">Price</th></tr></thead><tbody class="divide-y">@forelse($productList as $product)<tr><td class="p-4 font-bold">{{ $product->name }}</td><td class="p-4">{{ $product->owner?->name ?? '—' }}</td><td class="p-4">{{ ucfirst($product->status) }}</td><td class="p-4 font-black">₦{{ number_format((float)$product->price,2) }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-gray-500">No products.</td></tr>@endforelse</tbody></table></div><div class="p-4 border-t">{{ $productList->links() }}</div></div>
        @elseif(in_array($metric, ['commissions','payable','paid-commissions'], true))
            <div class="grid lg:grid-cols-3 gap-6"><div class="bg-white rounded-2xl border shadow-sm p-5"><h3 class="font-black">By commission level</h3><div class="mt-4 space-y-3">@forelse($byLevel as $row)<div class="flex justify-between border-b pb-3"><span>Level {{ $row->level }}</span><b>₦{{ number_format((float)$row->amount,2) }}</b></div>@empty<p class="text-sm text-gray-500">No commissions.</p>@endforelse</div></div><div class="bg-white rounded-2xl border shadow-sm p-5"><h3 class="font-black">Top recipients</h3><div class="mt-4 space-y-3">@forelse($byPartner as $row)<div class="flex justify-between border-b pb-3 gap-3"><span>{{ $row->partner?->user?->name ?? 'Partner' }} <small class="block text-gray-400">{{ $row->count }} allocations</small></span><b>₦{{ number_format((float)$row->amount,2) }}</b></div>@empty<p class="text-sm text-gray-500">No commissions.</p>@endforelse</div></div><div class="bg-white rounded-2xl border shadow-sm p-5"><h3 class="font-black">Commission totals</h3><p class="mt-4 text-3xl font-black">₦{{ number_format((float)$stats['commission_total'],2) }}</p><p class="text-xs text-gray-500 mt-1">Filtered platform commission total.</p></div></div>
            <div class="bg-white rounded-2xl border shadow-sm overflow-hidden"><div class="p-5 border-b"><h3 class="font-black">Commission allocation detail</h3></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50"><tr><th class="text-left p-4">Recipient</th><th class="text-left p-4">Order</th><th class="text-left p-4">Level</th><th class="text-left p-4">Status</th><th class="text-left p-4">Amount</th></tr></thead><tbody class="divide-y">@forelse($commissionList as $commission)<tr><td class="p-4 font-semibold">{{ $commission->partner?->user?->name ?? 'Partner' }}</td><td class="p-4">{{ $commission->order?->order_number ?? '—' }}</td><td class="p-4">Level {{ $commission->level }}</td><td class="p-4">{{ ucfirst($commission->status) }}</td><td class="p-4 font-black">₦{{ number_format((float)$commission->commission_amount,2) }}</td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-gray-500">No commission records.</td></tr>@endforelse</tbody></table></div><div class="p-4 border-t">{{ $commissionList->links() }}</div></div>
        @endif
    </div></div>
<script>
const series=@json($series),canvas=document.getElementById('analyticsChart'),ctx=canvas.getContext('2d');function draw(){const d=devicePixelRatio||1,w=canvas.clientWidth||900,h=220;canvas.width=w*d;canvas.height=h*d;ctx.scale(d,d);const max=Math.max(...series.map(x=>x.sales),1),l=45,r=12,t=12,b=30;ctx.strokeStyle='#e2e8f0';for(let i=0;i<4;i++){const y=t+(h-t-b)*i/3;ctx.beginPath();ctx.moveTo(l,y);ctx.lineTo(w-r,y);ctx.stroke()}if(!series.length)return;ctx.strokeStyle='#7c3aed';ctx.lineWidth=3;ctx.beginPath();series.forEach((p,i)=>{const x=l+(w-l-r)*i/Math.max(series.length-1,1),y=t+(h-t-b)*(1-p.sales/max);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#64748b';ctx.font='11px sans-serif';ctx.fillText(series[0].date,l,h-8);ctx.fillText(series.at(-1).date,w-80,h-8)}draw();addEventListener('resize',draw);
</script>
</x-app-layout>
